Update the column names
timescale/docs pull request #1022
Opened 2022-04-19 08:39 UTC by Rajakavitha1

# Description

The available columns in TimescaleDB are:

           View "timescaledb_information.hypertables"
       Column        |   Type   | Collation | Nullable | Default
---------------------+----------+-----------+----------+---------
 hypertable_schema   | name     |           |          |
 hypertable_name     | name     |           |          |
 owner               | name     |           |          |
 num_dimensions      | smallint |           |          |
 num_chunks          | bigint   |           |          |
 compression_enabled | boolean  |           |          |
 is_distributed      | boolean  |           |          |
 replication_factor  | smallint |           |          |
 data_nodes          | name[]   |           |          |
 tablespaces         | name[]   |           |          |

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes # https://github.com/timescale/docs/issues/1010

2022-04-19 23:39 UTC, svenklemm requested changes
Hmm where is the add_dimension change coming from, seems unrelated and is actually wrong cause the names for add_dimension seem to be correct.

2022-04-20 04:44 UTC, Rajakavitha1 commented
> Hmm where is the add_dimension change coming from, seems unrelated and is actually wrong cause the names for add_dimension seem to be correct.

Sorry!!! just reverted the changes.

2022-04-20 22:03 UTC, svenklemm approved these changes

2022-04-21 00:44 UTC, Loquacity approved these changes

2022-04-21 05:47 UTC, merged