Fix data types for `move_chunk` API reference
timescale/docs pull request #1033
Opened 2022-04-22 18:05 UTC by charislam

# Description

[Relevant Slack message](https://iobeam.slack.com/archives/CEKV5LMK3/p1650650375067429?thread_ts=1650648705.589909&cid=CEKV5LMK3)

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes #[insert issue link, if any]

2022-04-23 20:05 UTC, svenklemm approved these changes

2022-04-24 21:52 UTC, svenklemm requested changes
i just doublechecked and index_destination_tablespace is an optional argument

2022-04-25 03:20 UTC, Rajakavitha1 approved these changes
LGTM

2022-04-25 07:04 UTC, svenklemm commented
So the index_destination_tablespace line should be moved from required arguments section to optional arguments.

2022-05-01 19:36 UTC, svenklemm approved these changes

2022-05-02 15:16 UTC, merged