Add a warning about the API
timescale/docs pull request #1067
Opened 2022-05-06 09:44 UTC by zseta

2022-05-06 13:52 UTC, ryanbooz commented on timescaledb/tutorials/analyze-nft-data/nft-schema-ingestion.md
> +</highlight>
```suggestion
<highlight type="warning">
The following procedure relies on the OpenSea API provided and maintained by OpenSea. Unfortunately,
there have recently been extended periods of time when the API is not functioning, something that is
outside of our control. 

If the API has changed or is not accessible when you attempt to run the `opensea_ingest.py`, we suggest following the second procedure to download a historical data file and importing it. You will be able to successfully 
complete the tutorial with that data alone.
</highlight>
```

2022-05-09 03:22 UTC, Loquacity requested changes

2022-05-09 03:22 UTC, Loquacity commented on timescaledb/tutorials/analyze-nft-data/nft-schema-ingestion.md
> +complete the tutorial with that data alone.
```suggestion
This procedure relies on the OpenSea API. The OpenSea API is provided and 
maintained by OpenSea. Recently, the API is stopped functioning for extended 
periods of time. If the API has changed or is not accessible when you attempt 
to run the `opensea_ingest.py` script, try following the procedure to download 
an historical data file and import it. You can use this data file to complete the 
tutorial.
```

2022-05-09 13:47 UTC, ryanbooz approved these changes

2022-05-09 14:15 UTC, merged