Add APM experience Reference
timescale/docs pull request #1071
Opened 2022-05-08 20:19 UTC by VineethReddy02

# Description

Add details on how to import APM dashboards. 

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

2022-05-09 19:19 UTC, VineethReddy02 commented
Assigning it to @Rajakavitha1 for organizing the content of the doc and copy editing-related changes.

2022-05-11 22:48 UTC, VineethReddy02 commented on promscale/visualize-data/apm-experience.md
> +1.  Copy the content from the `.json` file from the above referenced Promscale dashboards.
agreed.

2022-05-11 23:02 UTC, ramonguiu approved these changes

2022-05-12 06:22 UTC, Loquacity requested changes

2022-05-12 06:22 UTC, Loquacity commented on promscale/visualize-data/apm-experience.md
> +
```suggestion
```

2022-05-12 06:22 UTC, Loquacity commented on promscale/visualize-data/apm-experience.md
> +## Before you begin importing APM dashboards
```suggestion
Before you begin importing APM dashboards:

```

2022-05-12 06:22 UTC, Loquacity commented on promscale/visualize-data/apm-experience.md
> +* Ensure that timescaledb_toolkit PostgreSQL extension is installed.
```suggestion
* Check that the `timescaledb_toolkit` extension is installed.
```

2022-05-12 06:22 UTC, Loquacity commented on promscale/visualize-data/apm-experience.md
> +<procedure>
```suggestion
<procedure> 

## Installing the TimescaleDB toolkit extension
```

2022-05-12 06:22 UTC, Loquacity commented on promscale/visualize-data/apm-experience.md
> +To install the timescaledb_toolkit PostgreSQL extension:
```suggestion

```

2022-05-12 06:22 UTC, Loquacity commented on promscale/visualize-data/apm-experience.md
> +   `SELECT * FROM pg_available_extensions WHERE name='timescaledb_toolkit';`
```suggestion
1.  Check if the extension is available:

    ```sql
    SELECT * 
      FROM pg_available_extensions 
      WHERE name='timescaledb_toolkit';
    ```

```

2022-05-12 06:22 UTC, Loquacity commented on promscale/visualize-data/apm-experience.md
> +   </highlight>
```suggestion
     If the query returns no results, the extension is not available for installation
     in your database. To make it available follow 
     [these instructions](install-toolkit). 
```

2022-05-12 06:22 UTC, Loquacity commented on promscale/visualize-data/apm-experience.md
> +1. Install the extension using: `CREATE EXTENSION timescaledb_toolkit;`
```suggestion
1. Install the extension:

     ```sql
     CREATE EXTENSION timescaledb_toolkit;
     ```

```

2022-05-12 06:22 UTC, Loquacity commented on promscale/visualize-data/apm-experience.md
> +*  When installing Grafana, mount APM dashboards as a snapshot.
This might need to go further up the page, before the procedure?

2022-05-12 06:22 UTC, Loquacity commented on promscale/visualize-data/apm-experience.md
> +
```suggestion
```

2022-05-12 06:22 UTC, Loquacity commented on promscale/visualize-data/apm-experience.md
> +[Grafana community dashboards](promscale-grafana-dashboards) contains all the
```suggestion
[Grafana community dashboards](promscale-grafana-dashboards) contain all the
```

2022-05-12 06:22 UTC, Loquacity commented on promscale/visualize-data/apm-experience.md
> +
Needs a procedure title

2022-05-12 06:22 UTC, Loquacity commented on promscale/visualize-data/apm-experience.md
> +1.  Click the `Details` button to open a dashboard from [Grafana community
Needs a location ... "In the Grafana dashboard" perhaps?

2022-05-12 06:22 UTC, Loquacity commented on promscale/visualize-data/apm-experience.md
> +1.  Select the data sources from which you want the dashboard to query the data.
```suggestion
1.  Select the data sources from which you want the dashboard to query the data:
```

2022-05-12 06:22 UTC, Loquacity commented on promscale/visualize-data/apm-experience.md
> +
Needs a procedure title

2022-05-12 06:22 UTC, Loquacity commented on promscale/visualize-data/apm-experience.md
> +
```suggestion
```

2022-05-12 06:22 UTC, Loquacity commented on promscale/visualize-data/apm-experience.md
> +1.  Select the data sources from which you want the dashboard to query the data.
```suggestion
1.  Select the data sources from which you want the dashboard to query the data:
```

2022-05-12 06:22 UTC, Loquacity commented on promscale/visualize-data/apm-experience.md
> +In that directory that is mounted to Grafana configuration, prefix `APM` to all
```suggestion
In the directory that is mounted to Grafana configuration, prefix `APM` to all
```

2022-05-12 06:22 UTC, Loquacity commented on promscale/visualize-data/apm-experience.md
> +the dashboards with APM as prefix from [Promscale Github repository](promscale-github-dashboards).
```suggestion
the dashboards from [Promscale Github repository](promscale-github-dashboards). 
```

2022-05-12 08:43 UTC, Rajakavitha1 commented on promscale/visualize-data/apm-experience.md
> +
done

2022-05-12 09:12 UTC, Rajakavitha1 approved these changes

2022-05-12 21:43 UTC, merged