Update resource recommendation guide for Promscale
timescale/docs pull request #1084
Opened 2022-05-10 20:03 UTC by VineethReddy02

# Description

Added Prometheus `remote_write` recommended config and TimescaleDB recommended configuration. 

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes #[insert issue link, if any]

2022-05-11 07:57 UTC, Rajakavitha1 approved these changes

2022-05-12 04:01 UTC, Loquacity requested changes

2022-05-12 04:01 UTC, Loquacity commented on promscale/installation/recomm-guide.md
> +  delay
```suggestion
* `bgwriter_delay=10ms` - the background writer needs to be active to reduce
  delays.
```

2022-05-12 04:01 UTC, Loquacity commented on promscale/installation/recomm-guide.md
> +Promscale connector and the database is no more than `100ms`. </highlight>
```suggestion
<highlight type="important"> 
Make sure that the maximum latency between the
Promscale connector and the database is no more than 100ms. 
</highlight>
```

2022-05-12 04:01 UTC, Loquacity commented on promscale/installation/recomm-guide.md
> +    timescaledb/:currentVersion:/how-to-guides/configuration/timescaledb-tune/
```suggestion
[timescale-tune-configuration]: timescaledb/:currentVersion:/how-to-guides/configuration/timescaledb-tune/
```

2022-05-12 05:33 UTC, Loquacity approved these changes

2022-05-12 14:31 UTC, VineethReddy02 commented
closing this in favor to #1093

2022-05-12 14:31 UTC, closed without merging