Restructure migrate how-to to fit new template
timescale/docs pull request #1094
Opened 2022-05-12 22:13 UTC by charislam

# Description

Restructure migrate how-to to fit new template

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Partial #60

2022-05-13 03:46 UTC, Loquacity commented on timescaledb/how-to-guides/migrate-data/index.md
> +*   Migrate data when TimescaleDB is in the [same PostgreSQL instance][same-db]
Don't forget to add in the "Learn about data migration ..." point at the top.

2022-05-13 15:23 UTC, charislam commented on timescaledb/how-to-guides/migrate-data/index.md
> +*   Migrate data when TimescaleDB is in the [same PostgreSQL instance][same-db]
```suggestion
*   [Learn about data migration][about-data-migration] before you start
*   Migrate data when TimescaleDB is in the [same PostgreSQL instance][same-db]
```

2022-05-16 03:59 UTC, Loquacity requested changes

2022-05-16 03:59 UTC, Loquacity commented on timescaledb/how-to-guides/migrate-data/import-csv.md
> +`timescaledb-parallel-copy`, you can also use regular PostgreSQL `COPY`.
```suggestion
Timescale provides an open source 
[parallel importer](https://github.com/timescale/timescaledb-parallel-copy) program,
`timescaledb-parallel-copy`, to speed up data copying. The program parallelizes
migration by using several workers to run multiple `COPY`s concurrently. It also
offers options to improve the copying experience. If you prefer not to download
`timescaledb-parallel-copy`, you can also use regular PostgreSQL `COPY`. 
```

2022-05-16 03:59 UTC, Loquacity commented on timescaledb/how-to-guides/migrate-data/import-csv.md
> +1.  **(Alternative)** If you don't want to use `timescaledb-parallel-copy`,
```suggestion
1.  **OPTIONAL** If you don't want to use `timescaledb-parallel-copy`,
```

2022-05-16 03:59 UTC, Loquacity commented on timescaledb/how-to-guides/migrate-data/same-db.md
> +    indexes.
```suggestion
1.  If you created your new table without indexes, recreate your indexes now.
```

Does this need a command?

2022-05-16 03:59 UTC, Loquacity commented on timescaledb/how-to-guides/migrate-data/troubleshooting.md
> +
Can we add the boilerplate Troubleshooting stuff in here? You can see it in the caggs section.

2022-05-17 00:36 UTC, Loquacity approved these changes

2022-05-17 14:37 UTC, merged