[Update] default value of `timescaledb.max_background_workers` to 16
timescale/docs pull request #1111
Opened 2022-05-18 03:23 UTC by Rajakavitha1

# Description

Updated the default value of timescaledb.max_background_workers to 16
# Links

Fixes https://github.com/timescale/docs/issues/1099
# Review checklists
Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

- [ ] Is the content technically accurate?
- [ ] Is the content complete?
- [ ] Is the content presented in a logical order?
- [ ] Does the content use appropriate names for features and products?
- [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

- [ ] Is the content free from typos?
- [ ] Does the content use plain English?
- [ ] Does the content contain clear sections for concepts, tasks, and references?
- [ ] Are procedure and highlight tags used appropriately?
- [ ] Has the index been updated appropriately?
- [ ] Have any images been uploaded to the correct location, and are resolvable?
- [ ] Are all links provided in reference style, and resolvable?
- [ ] Have you checked the built version of this content?

2022-05-18 03:34 UTC, Loquacity requested changes

2022-05-18 03:34 UTC, Loquacity commented on timescaledb/how-to-guides/configuration/about-configuration.md
> +number of concurrent background workers you want running at any one time. By default, `timescaledb-tune` sets `timescaledb.max_background_workers` to 16. You can change this setting directly, use the
```suggestion
number of concurrent background workers you want running at any one time. By 
default, `timescaledb-tune` sets `timescaledb.max_background_workers` to 16. 
You can change this setting directly, use the `--max-bg-workers` flag, or adjust 
the `TS_TUNE_MAX_BG_WORKERS` 
[Docker environment variable][docker-conf].
```

2022-05-20 00:37 UTC, Loquacity approved these changes

2022-05-20 07:03 UTC, konskov approved these changes

2022-05-20 07:47 UTC, merged