[Update] links to information views
timescale/docs pull request #1135
Opened 2022-05-26 07:10 UTC by Rajakavitha1

# Description

Based on the discussion in: https://www.timescale.com/forum/t/get-compression-policy/286
"I see the functions “add_compression_policy” and “remove_compression_policy”. What do I use to check current existing compression policy or policies?"

Added links to informational-view in relevant sections.
# Links

Fixes #[insert issue link, if any]

# Review checklists
Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

- [ ] Is the content technically accurate?
- [ ] Is the content complete?
- [ ] Is the content presented in a logical order?
- [ ] Does the content use appropriate names for features and products?
- [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

- [ ] Is the content free from typos?
- [ ] Does the content use plain English?
- [ ] Does the content contain clear sections for concepts, tasks, and references?
- [ ] Are procedure and highlight tags used appropriately?
- [ ] Has the index been updated appropriately?
- [ ] Have any images been uploaded to the correct location, and are resolvable?
- [ ] Are all links provided in reference style, and resolvable?
- [ ] If the page index was updated, are redirects required
      and have they been implemented?
- [ ] Have you checked the built version of this content?

2022-05-26 07:32 UTC, Loquacity requested changes

2022-05-26 07:32 UTC, Loquacity commented on api/actions.md
> +views][informational-views].
```suggestion
continuous aggregation refresh policies and data retention policies. To view the
policies that you set or the policies that already exist, see 
[informational views][informational-views].
```

2022-05-26 07:32 UTC, Loquacity commented on api/add_compression_policy.md
> +already exist, see [informational views][informational-views].
```suggestion
aggregates that already have compression enabled. Use the 
[`ALTER TABLE`][compression_alter-table] command to set `timescaledb.compress` 
and other configuration parameters for hypertables. Use 
[`ALTER MATERIALIZED VIEW`][compression_continuous-aggregate] command to 
enable compression on continuous aggregates. To view the policies that you set or 
the policies that already exist, see 
[informational views][informational-views].
```

2022-05-26 07:32 UTC, Loquacity commented on api/add_continuous_aggregate_policy.md
> +views][informational-views].
```suggestion
policies that you set or the policies that already exist, see 
[informational views][informational-views].
```

2022-05-26 07:32 UTC, Loquacity commented on api/remove_compression_policy.md
> +If you need to remove the compression policy. To re-start policy-based
```suggestion
If you need to remove the compression policy. To restart policy-based
```

2022-05-26 07:32 UTC, Loquacity commented on api/remove_compression_policy.md
> +compression again you need to re-add the policy. To view the policies that
```suggestion
compression you need to add the policy again. To view the policies that
```

2022-05-27 00:26 UTC, Loquacity approved these changes

2022-06-21 14:42 UTC, mirandaauhl approved these changes
Looks great!

2022-07-08 08:04 UTC, merged