[Cloud scaling] Add warning about optimizing time
timescale/docs pull request #1169
Opened 2022-06-07 18:52 UTC by charislam

# Description

[Short summary of why you created this PR]

# Links

Fixes #[insert issue link, if any]

# Review checklists
Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

- [ ] Is the content technically accurate?
- [ ] Is the content complete?
- [ ] Is the content presented in a logical order?
- [ ] Does the content use appropriate names for features and products?
- [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

- [ ] Is the content free from typos?
- [ ] Does the content use plain English?
- [ ] Does the content contain clear sections for concepts, tasks, and references?
- [ ] Are procedure and highlight tags used appropriately?
- [ ] Has the index been updated appropriately?
- [ ] Have any images been uploaded to the correct location, and are resolvable?
- [ ] Are all links provided in reference style, and resolvable?
- [ ] If the page index was updated, are redirects required
      and have they been implemented?
- [ ] Have you checked the built version of this content?

2022-06-09 07:09 UTC, mwarejohn reviewed
Is it okay to modify line 148, where it says `The 125GB tier takes 6 to 24 hours to optimize` and instead say:
`Storage resize operation involves modifying the underlying EBS volume which can take from a few minutes to a few hours depending on the configuration changes being applied. E.g an EBS volume of size 1 TiB can typically take up to 6 hours to be modified. However, the same volume might take up to 24 hours in other situations. The time taken for volumes to be modified doesn't always scale linearly. Therefore, a larger volume might take less time, and a smaller volume might take more time.`

This allows us to stick close to [this AWS doc](https://aws.amazon.com/premiumsupport/knowledge-center/ebs-volume-stuck-optimizing-on-modification/).

2022-06-09 15:23 UTC, charislam commented
> Is it okay to modify line 148, where it says `The 125GB tier takes 6 to 24 hours to optimize` and instead say: `Storage resize operation involves modifying the underlying EBS volume which can take from a few minutes to a few hours depending on the configuration changes being applied. E.g an EBS volume of size 1 TiB can typically take up to 6 hours to be modified. However, the same volume might take up to 24 hours in other situations. The time taken for volumes to be modified doesn't always scale linearly. Therefore, a larger volume might take less time, and a smaller volume might take more time.`
> 
> This allows us to stick close to [this AWS doc](https://aws.amazon.com/premiumsupport/knowledge-center/ebs-volume-stuck-optimizing-on-modification/).

Of course! I tried to capture the main messages without distracting from the flow of this particular example or outright copying the AWS docs:

`For example, say you have 100&nbsp;GB of storage. The next two tiers are
125&nbsp;GB and 150&nbsp;GB. To resize to 125&nbsp;GB, AWS needs to modify the
underlying storage volume. This can typically happen within 6 hours, but it
might take 24 hours in some cases. The time doesn't always scale linearly with
the volume size. For safety, you might want to leave 24 hours.`

2022-06-09 15:48 UTC, mwarejohn approved these changes
Thank you @charislam. Looks okay.

2022-06-14 03:18 UTC, Loquacity requested changes

2022-06-14 03:18 UTC, Loquacity commented on cloud/service-operations/autoscaling.md
> +behind the scenes. Optimization takes anywhere from 6 to 24 hours for each TB of
```suggestion
behind the scenes. Optimization takes anywhere from 6 to 24 hours for each terabyte of
```

2022-06-14 03:18 UTC, Loquacity commented on cloud/service-operations/autoscaling.md
> +[manually scale your database](#change-resource-allocations-manually) to your
Can we switch these links to reference style?

2022-06-15 00:32 UTC, Loquacity approved these changes

2022-06-15 16:23 UTC, merged