[Compression] Update backfill-procedure support
timescale/docs pull request #1257
Opened 2022-07-04 23:22 UTC by charislam

# Description

The `decompress_backfill` procedure only supports regular hypertables,
not distributed hypertables.

+ some drive-by edits

# Links

Fixes #1250 

# Review checklists
Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

- [ ] Is the content technically accurate?
- [ ] Is the content complete?
- [ ] Is the content presented in a logical order?
- [ ] Does the content use appropriate names for features and products?
- [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

- [ ] Is the content free from typos?
- [ ] Does the content use plain English?
- [ ] Does the content contain clear sections for concepts, tasks, and references?
- [ ] Are procedure and highlight tags used appropriately?
- [ ] Has the index been updated appropriately?
- [ ] Have any images been uploaded to the correct location, and are resolvable?
- [ ] Are all links provided in reference style, and resolvable?
- [ ] If the page index was updated, are redirects required
      and have they been implemented?
- [ ] Have you checked the built version of this content?

2022-07-05 04:46 UTC, Loquacity requested changes
Sorry, I'm doing drive-bys as well 😳

2022-07-05 04:46 UTC, Loquacity commented on timescaledb/how-to-guides/compression/backfill-historical-data.md
> +a compressed chunk.
```suggestion
individual row inserts). When you backfill data, you insert data corresponding to
a timestamp well in the past, which has a timestamp that already corresponds to
a compressed chunk.
```

2022-07-05 04:46 UTC, Loquacity commented on timescaledb/how-to-guides/compression/backfill-historical-data.md
> +## Future Work
```suggestion
## Future work
```

2022-07-05 04:46 UTC, Loquacity commented on timescaledb/how-to-guides/compression/backfill-historical-data.md
>  If using a temp table, the table is automatically dropped at the end of your
```suggestion
If you are using a temporary table, the table is automatically dropped at the end of your
```

2022-07-05 04:46 UTC, Loquacity commented on timescaledb/how-to-guides/compression/backfill-historical-data.md
>  database session. If using a normal table, after you are done backfilling the
```suggestion
database session. If you are using a regular table, after you have backfilled the
```

2022-07-05 06:14 UTC, jnidzwetzki commented on timescaledb/how-to-guides/compression/backfill-historical-data.md
> +backfill a distributed hypertable, manually decompress the chunks.
By adding "...before the data is inserted." to the end of the sentence, the user might be able to understand it better.

2022-07-05 06:15 UTC, jnidzwetzki approved these changes

2022-07-05 17:31 UTC, charislam commented on timescaledb/how-to-guides/compression/backfill-historical-data.md
> +backfill a distributed hypertable, manually decompress the chunks.
```suggestion
backfill a distributed hypertable, manually decompress the chunks before inserting data.
```

2022-07-06 02:26 UTC, Loquacity approved these changes

2022-07-06 17:31 UTC, merged