[Cloud multi-node] Add new approval steps
timescale/docs pull request #1280
Opened 2022-07-07 16:00 UTC by charislam

# Description

Add new approval steps for setting up multi-node.

# Links

Fixes https://github.com/timescale/docs-private/issues/34

# Review checklists
Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

- [ ] Is the content technically accurate?
- [ ] Is the content complete?
- [ ] Is the content presented in a logical order?
- [ ] Does the content use appropriate names for features and products?
- [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

- [ ] Is the content free from typos?
- [ ] Does the content use plain English?
- [ ] Does the content contain clear sections for concepts, tasks, and references?
- [ ] Are procedure and highlight tags used appropriately?
- [ ] Has the index been updated appropriately?
- [ ] Have any images been uploaded to the correct location, and are resolvable?
- [ ] Are all links provided in reference style, and resolvable?
- [ ] If the page index was updated, are redirects required
      and have they been implemented?
- [ ] Have you checked the built version of this content?

2022-07-08 01:02 UTC, Loquacity requested changes

2022-07-08 01:02 UTC, Loquacity commented on cloud/cloud-multi-node.md
> +1.  If this is your first multi-node service, a contact form appears. Multi-node
```suggestion
1.  If this is your first multi-node service, you see a contact form. Multi-node
```

2022-07-08 01:02 UTC, Loquacity commented on cloud/cloud-multi-node.md
> +    is currently available on request. A conversation with our customer support
```suggestion
    is currently available on request. A conversation with the Timescale customer support
```

2022-07-08 01:02 UTC, Loquacity commented on cloud/cloud-multi-node.md
> +1.  Our customer support team will contact you. Once your request is approved,
```suggestion
1.  Our customer support team contacts you. When your request is approved,
```

2022-07-11 02:19 UTC, Loquacity commented on cloud/cloud-multi-node.md
> +1.  Our customer support team contacts you. When your request is approved,
```suggestion
1.  The customer support team contacts you. When your request is approved,
```

2022-07-11 02:20 UTC, Loquacity approved these changes

2022-07-11 07:17 UTC, lukas-bernert approved these changes

2022-07-11 16:32 UTC, merged