[update] added partials for installing psql
timescale/docs pull request #1603
Opened 2022-09-15 06:51 UTC by Rajakavitha1

# Description

Added installing psql to install sections so that the users have all the information to install, connect, and set up a DB on one page.

PS: I was not able to build locally to check the changes because i kept getting:
<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1013221f5 node::Abort() (.cold.1) [/Users/rajakavithakodhandapani/.nvm/versions/node/v14.19.1/bin/node]
 2: 0x1000b6399 node::Abort() [/Users/rajakavithakodhandapani/.nvm/versions/node# Links

Fixes #[insert issue link, if any]

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/timescaledb/latest/contribute-to-docs/)

# Review checklists
Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

- [ ] Is the content technically accurate?
- [ ] Is the content complete?
- [ ] Is the content presented in a logical order?
- [ ] Does the content use appropriate names for features and products?
- [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

- [ ] Is the content free from typos?
- [ ] Does the content use plain English?
- [ ] Does the content contain clear sections for concepts, tasks, and references?
- [ ] Have any images been uploaded to the correct location, and are resolvable?
- [ ] If the page index was updated, are redirects required
      and have they been implemented?
- [ ] Have you checked the built version of this content?

2022-09-15 15:40 UTC, charislam requested changes
To make sure we are reusing content and not creating partials that are only used once, we might want to edit the [psql install page](https://docs.timescale.com/timescaledb/latest/how-to-guides/connecting/psql/) to make use of the new partials.

I built this locally and didn't see any errors, so I haven't been able to replicate the build issues yet. Let me know if they persist and I can do some more debugging!

2022-09-15 15:40 UTC, charislam commented on install/installation-macos.md
> +<MacPorts />
See comment for Homebrew.

2022-09-16 02:19 UTC, Loquacity commented
Seems to be missing from the RHEL and Arch instructions, too.

2022-09-16 03:15 UTC, Rajakavitha1 commented
> Seems to be missing from the RHEL and Arch instructions, too.

Yes!!! that is right @Loquacity . The original install psql content does not have instructions for those.  I am going to spin up a RHEL and Arch instance install psql and then add the partials.

2022-09-16 07:15 UTC, Rajakavitha1 commented on install/installation-macos.md
> +<Homebrew />
added the intro sentence for psql

2022-09-16 07:15 UTC, Rajakavitha1 commented on install/installation-macos.md
> +<MacPorts />
updated

2022-09-16 07:30 UTC, Loquacity commented on install/installation-macos.md
> +Connect to it PostgreSQL from your local system using the `psql` command-line
```suggestion
Connect to PostgreSQL from your local system using the `psql` command-line
```

2022-09-16 07:30 UTC, Loquacity approved these changes

2022-09-16 07:55 UTC, Rajakavitha1 commented
> To make sure we are reusing content and not creating partials that are only used once, we might want to edit the [psql install page](https://docs.timescale.com/timescaledb/latest/how-to-guides/connecting/psql/) to make use of the new partials.
> 
> I built this locally and didn't see any errors, so I haven't been able to replicate the build issues yet. Let me know if they persist and I can do some more debugging!

Yes!!! I agree. I will work on the psql client install instructions for arch Linux and RHEL and then use the partials in the install psql page. Is that okay?

2022-09-16 14:36 UTC, charislam approved these changes

2022-09-16 15:20 UTC, merged