Add small note about timescale dependent objects
timescale/docs pull request #165
Opened 2021-07-09 14:24 UTC by jonatas

# Description

[Short summary of why you created this PR]

# Version

Which documentation version does this PR apply to?

- [ ] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes #[insert issue link, if any]

2021-07-09 15:39 UTC, sgichohi approved these changes
Awesome

2021-07-12 01:39 UTC, Loquacity requested changes
Just a wording suggestion.

2021-07-12 01:39 UTC, Loquacity commented on timescaledb/tutorials/custom-timescaledb-dashboards.md
> +</highlight>
```suggestion
<highlight type="warning">
The view is dependent on TimescaleDB internals. You might need to drop the view
to upgrade the TimescaleDB extension, and recreate it after the upgrade.
</highlight>
```

2021-07-12 23:02 UTC, Loquacity approved these changes

2021-07-12 23:02 UTC, merged