Update data node management with example of moving a chunk
timescale/docs pull request #174
Opened 2021-07-13 13:53 UTC by erimatnor

The data node management section now has a basic description of moving
a chunk between data nodes. This complements the section on adding new
data nodes (elasticity) with information on how to actually get data
to a new node.

The information on copying and moving chunks is now split across the
data node management section and the native replication section. In
the future, we might want to rewrite this to have everything about
copying and moving chunks in a single place.

# Version

Which documentation version does this PR apply to?

- [x ] Latest (Default)
- [x ] Version 2.4

2021-07-14 00:57 UTC, Loquacity requested changes
Just small edits, non-blocking.

2021-07-14 00:57 UTC, Loquacity commented on timescaledb/how-to-guides/distributed-hypertables/manage-data-nodes.md
>  using [`attach_data_node`][attach_data_node]:
```suggestion
If you add additional data nodes to a database, they are
not automatically associated with existing distributed
hypertables. Instead, you need to explicitly attach a data node
using [`attach_data_node`][attach_data_node]:
```

2021-07-14 00:57 UTC, Loquacity commented on timescaledb/how-to-guides/distributed-hypertables/manage-data-nodes.md
>  When attaching a data node, the partitioning configuration of the
```suggestion
When you attach a data node, the partitioning configuration of the
```

2021-07-14 00:57 UTC, Loquacity commented on timescaledb/how-to-guides/distributed-hypertables/manage-data-nodes.md
> +the data node will be able to take on newly created chunks.
```suggestion
data node (the number of space partitions are automatically
increased to match), unless the function parameter `repartition` is
set to `FALSE`. The updated partitioning configuration ensures that
the data node is able to take on newly created chunks.
```

2021-07-14 00:57 UTC, Loquacity commented on timescaledb/how-to-guides/distributed-hypertables/manage-data-nodes.md
> +moved between nodes at the chunk level:
```suggestion
When you attach a new data node to a distributed hypertable, you might
prefer to move data to the new node to free up storage on the
existing nodes and make queries use the added capacity. Data can be
moved between nodes at the chunk level:
```

2021-07-14 00:57 UTC, Loquacity commented on timescaledb/how-to-guides/distributed-hypertables/manage-data-nodes.md
> +</highlight>
```suggestion
<highlight type="warning"> 
The ability to move chunks between data nodes is an experimental
feature that is under active development. We recommend that you
do not use this feature in a production environment.
</highlight>
```

2021-07-14 09:41 UTC, NunoFilipeSantos approved these changes
I agree with @Loquacity 's suggestions.

2021-07-27 00:25 UTC, Loquacity approved these changes

2021-07-27 00:26 UTC, Loquacity commented
@erimatnor Ready to merge 👍

2021-07-27 09:49 UTC, NunoFilipeSantos commented
To follow the release of 2.4.

2021-08-03 12:38 UTC, merged