Adds new example to first/last agg API docs
timescale/docs pull request #1813
Opened 2022-11-28 01:35 UTC by Loquacity

# Description

Adds new example to API docs for first/last aggs.

# Links

Fixes https://github.com/timescale/docs/issues/1787

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/timescaledb/latest/contribute-to-docs/)

# Review checklists
Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

- [ ] Is the content technically accurate?
- [ ] Is the content complete?
- [ ] Is the content presented in a logical order?
- [ ] Does the content use appropriate names for features and products?
- [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

- [ ] Is the content free from typos?
- [ ] Does the content use plain English?
- [ ] Does the content contain clear sections for concepts, tasks, and references?
- [ ] Have any images been uploaded to the correct location, and are resolvable?
- [ ] If the page index was updated, are redirects required
      and have they been implemented?
- [ ] Have you checked the built version of this content?

2022-11-28 08:32 UTC, svenklemm approved these changes

2022-11-28 17:41 UTC, charislam requested changes
I am very confused, I thought the original issue was addressing these two APIs:

https://docs.timescale.com/api/latest/hyperfunctions/first/
https://docs.timescale.com/api/latest/hyperfunctions/last/

The code examples don't make sense to me on the pages where they're inserted because they're not using the hyperfunction aggregator (`counter_agg` or `timeweight`).

2022-11-29 03:02 UTC, Loquacity commented
> I am very confused, I thought the original issue was addressing these two APIs:
> 
> https://docs.timescale.com/api/latest/hyperfunctions/first/ https://docs.timescale.com/api/latest/hyperfunctions/last/
> 
> The code examples don't make sense to me on the pages where they're inserted because they're not using the hyperfunction aggregator (`counter_agg` or `timeweight`).

Hrm, I can put them there instead.

2022-12-01 06:39 UTC, charislam approved these changes

2022-12-05 03:38 UTC, merged