Switch from FFF to epoch
timescale/docs pull request #2015
Opened 2023-02-07 04:16 UTC by Loquacity

# Description

Updates the time section in the caggs How To to use Unix Epoch rather than the joke FFF system.

# Links

Fixes https://github.com/timescale/docs/issues/1843

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/timescaledb/latest/contribute-to-docs/)

# Review checklists
Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

- [ ] Is the content technically accurate?
- [ ] Is the content complete?
- [ ] Is the content presented in a logical order?
- [ ] Does the content use appropriate names for features and products?
- [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

- [ ] Is the content free from typos?
- [ ] Does the content use plain English?
- [ ] Does the content contain clear sections for concepts, tasks, and references?
- [ ] Have any images been uploaded to the correct location, and are resolvable?
- [ ] If the page index was updated, are redirects required
      and have they been implemented?
- [ ] Have you checked the built version of this content?

2023-02-07 10:33 UTC, bithead2k requested changes
All the verbiage looks good and the edits are sane.  Just need the 3 simple changes.

2023-02-07 10:33 UTC, bithead2k commented on timescaledb/how-to-guides/continuous-aggregates/time.md
> +      chunk_time_interval => 10);
I meant to change this to 20 minutes, and the time_bucket to 10.

2023-02-07 10:33 UTC, bithead2k commented on timescaledb/how-to-guides/continuous-aggregates/time.md
> +    SELECT EXTRACT(EPOCH FROM CURRENT_EPOCH)::bigint;
Need the closing quotes after the function:
SELECT EXTRACT(EPOCH FROM CURRENT_EPOCH)::bigint;
$$

2023-02-07 22:49 UTC, Loquacity commented on timescaledb/how-to-guides/continuous-aggregates/time.md
> +      chunk_time_interval => 10);
```suggestion
      chunk_time_interval => 20);
```

2023-02-07 22:50 UTC, Loquacity commented on timescaledb/how-to-guides/continuous-aggregates/time.md
> +    SELECT EXTRACT(EPOCH FROM CURRENT_EPOCH)::bigint;
```suggestion
    SELECT EXTRACT(EPOCH FROM CURRENT_EPOCH)::bigint;$$;
```

2023-02-08 05:07 UTC, Rajakavitha1 approved these changes

2023-02-08 16:32 UTC, bithead2k approved these changes
All set AFAICT

2023-02-09 00:43 UTC, merged