Kbase migration - User perms
timescale/docs pull request #225
Opened 2021-08-02 05:11 UTC by Loquacity

# Description

Migrate https://kb.timescale.cloud/en/articles/2752453-inviting-team-members-and-managing-privileges to docs

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes #[insert issue link, if any]

2021-08-03 00:22 UTC, Loquacity commented on timescale-cloud/user-management.md
> +<highlight="important">
```suggestion
<highlight type="important">
```

2021-08-18 19:19 UTC, ryanbooz requested changes

2021-08-18 19:19 UTC, ryanbooz commented on timescale-cloud/user-management.md
> +TimescaleDB (MST) console. New users can be added to an entire project, or a
```suggestion
You can add new users, and manage existing users, in the Timescale Cloud console. New users can be added to an entire project, or a
```

2021-08-18 19:19 UTC, ryanbooz commented on timescale-cloud/user-management.md
> +1.  [Log in to your MST account][mst-login]. By default, you start in the
```suggestion
1.  [Log in to your Timescale Cloud account][mst-login]. By default, you start in the
```

2021-08-18 19:19 UTC, ryanbooz commented on timescale-cloud/user-management.md
> +1.  [Log in to your MST account][mst-login]. By default, you start in the
```suggestion
1.  [Log in to your Timescale Cloud account][mst-login]. By default, you start in the
```

2021-08-19 00:06 UTC, Loquacity commented
![image](https://user-images.githubusercontent.com/3914967/129987459-06f0d0db-10c1-446c-b7bd-54f6bd48cc0b.png)

2021-08-24 12:15 UTC, ryanbooz approved these changes

2021-08-24 12:29 UTC, merged