Make unix_now function immutable, not stable
timescale/docs pull request #2275
Opened 2023-04-17 03:08 UTC by Loquacity

# Description

Update the example to use unix_now function as immutable instead of stable

# Links

Fixes https://github.com/timescale/docs/issues/2158

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs/)

# Review checklists

Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

*   [ ] Is the content technically accurate?
*   [ ] Is the content complete?
*   [ ] Is the content presented in a logical order?
*   [ ] Does the content use appropriate names for features and products?
*   [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

*   [ ] Is the content free from typos?
*   [ ] Does the content use plain English?
*   [ ] Does the content contain clear sections for concepts, tasks, and references?
*   [ ] Have any images been uploaded to the correct location, and are resolvable?
*   [ ] If the page index was updated, are redirects required
      and have they been implemented?
*   [ ] Have you checked the built version of this content?

2023-04-17 03:21 UTC, Rajakavitha1 approved these changes

2023-04-18 05:57 UTC, lkshminarayanan approved these changes

2023-04-18 06:23 UTC, svenklemm requested changes
This is not correct. This function is not immutable and if we include an example like that we should warn about the side effects of this incorrect declaration.

https://www.postgresql.org/docs/current/xfunc-volatility.html

2023-04-18 06:39 UTC, Loquacity commented
> This is not correct. This function is not immutable and if we include an example like that we should warn about the side effects of this incorrect declaration.
> 
> https://www.postgresql.org/docs/current/xfunc-volatility.html

OK, so how should we rewrite the example? Or is it just a bad example, and we should delete it?

2023-04-18 11:04 UTC, svenklemm commented
> > This is not correct. This function is not immutable and if we include an example like that we should warn about the side effects of this incorrect declaration.
> > https://www.postgresql.org/docs/current/xfunc-volatility.html
> 
> OK, so how should we rewrite the example? Or is it just a bad example, and we should delete it?

So while we are lying about the properties of the function here, it might be beneficial to do so in certain situations as it will enable certain optimizations in postgresql. The downside is that this can lead to incorrect query results when used with prepared statements. So we should put a disclaimer about incorrect results when adding an example like that.

2023-04-19 03:31 UTC, svenklemm approved these changes

2023-04-19 04:17 UTC, merged