Document next_start calculation on job failure
timescale/docs pull request #2329
Opened 2023-05-02 09:37 UTC by konskov

# Description

[Short summary of why you created this PR]

# Links

Fixes #[insert issue link, if any]

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs/)

# Review checklists

Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

*   [ ] Is the content technically accurate?
*   [ ] Is the content complete?
*   [ ] Is the content presented in a logical order?
*   [ ] Does the content use appropriate names for features and products?
*   [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

*   [ ] Is the content free from typos?
*   [ ] Does the content use plain English?
*   [ ] Does the content contain clear sections for concepts, tasks, and references?
*   [ ] Have any images been uploaded to the correct location, and are resolvable?
*   [ ] If the page index was updated, are redirects required
      and have they been implemented?
*   [ ] Have you checked the built version of this content?

2023-05-02 10:07 UTC, Rajakavitha1 requested changes

2023-05-02 10:07 UTC, Rajakavitha1 commented on api/alter_job.md
> +However, as we don’t want to put off the next start indefinitely or produce timestamps so large they end up out of range, we cap this at 5* schedule_interval, and we also do not consider more than 20
```suggestion
However, to ensure that the `next start time` is not put off indefinitely or produce timestamps so large they end up out of range, it is capped at 5* `schedule_interval`. Also, more than 20 consecutive failures are not considered, so if the number of consecutive failures is higher, then it multiplies by 20.
```

2023-05-02 10:07 UTC, Rajakavitha1 commented on api/alter_job.md
> +Additionally in the case of jobs with fixed schedules, we make sure that if the next start calculated as above, surpasses the next scheduled execution, then the job is executed again at the next sche
```suggestion
Additionally, in the case of jobs with fixed schedules, the system ensures that if the next start calculated as specified, surpasses the next scheduled execution, then the job is executed again at the next scheduled slot and not after that. This ensures that the job does not miss scheduled executions.
```

2023-05-02 10:07 UTC, Rajakavitha1 commented on api/alter_job.md
> +Finally, we distinguish between runtime failures that do not cause the job to crash and job crashes.
```suggestion
Finally, there is a distinction between runtime failures that do not cause the job to crash and job crashes.
```

2023-05-02 10:07 UTC, Rajakavitha1 commented on api/alter_job.md
> +but it will always be at least 5 minutes after the job's last finish, to give an operator enough time to disable it before another crash.
```suggestion
but it is always be at least 5 minutes after the job's last finish, to give an operator enough time to disable it before another crash.
```

2023-05-02 12:19 UTC, konskov commented on api/alter_job.md
> +The next_start is calculated using the following formula:
updated as requested

2023-05-02 12:19 UTC, konskov commented on api/alter_job.md
> +However, as we don’t want to put off the next start indefinitely or produce timestamps so large they end up out of range, we cap this at 5* schedule_interval, and we also do not consider more than 20
updated as requested

2023-05-02 12:42 UTC, Rajakavitha1 approved these changes
Checked the build preview here: http://docs-dev.timescale.com/docs-konskov-document_failures_retry_period/api/konskov-document_failures_retry_period/actions/alter_job/

2023-05-02 13:44 UTC, Rajakavitha1 commented on api/alter_job.md
> +
<Highlight type="note">

2023-05-02 13:44 UTC, Rajakavitha1 commented on api/alter_job.md
> +However, to ensure that the `next_start` time is not put off indefinitely or produce timestamps so large they end up out of range, it is capped at 5*`schedule_interval`.
```suggestion
To ensure that the `next_start` time is not put off indefinitely or produce timestamps so large they end up out of range, it is capped at 5*`schedule_interval`.
```

2023-05-02 13:49 UTC, Rajakavitha1 commented on api/alter_job.md
> +
<Highlight type="note">

2023-05-04 06:17 UTC, konskov commented on api/alter_job.md
> +plus some jitter (± 13%) to avoid the “thundering herds” effect.
It feels to me that this phrasing implies that adding jitter is up to the user, when in fact is always added and the user can't control it. So, I wanted to confirm with you before making the suggested change whether that is the meaning we convey here or not?

2023-05-04 06:26 UTC, Loquacity commented on api/alter_job.md
> +plus some jitter (± 13%) to avoid the “thundering herds” effect.
Watch those smart quotes, too.

```suggestion
plus some jitter (± 13%) to avoid the "thundering herds" effect.
```

2023-05-04 09:21 UTC, Rajakavitha1 commented on api/alter_job.md
> +plus some jitter (± 13%) to avoid the “thundering herds” effect.
> It feels to me that this phrasing implies that adding jitter is up to the user, when in fact is always added and the user can't control it. So, I wanted to confirm with you before making the suggested change whether that is the meaning we convey here or not?

In that case, maybe you want to add it as a part of the calculation formula.

2023-05-08 06:27 UTC, konskov commented on api/alter_job.md
> +plus some jitter (± 13%) to avoid the “thundering herds” effect.
I made a slight change there

2023-05-08 06:30 UTC, Rajakavitha1 approved these changes

2023-05-08 06:34 UTC, merged