Update Hypershift docs for v0.6
timescale/docs pull request #2410
Opened 2023-05-31 13:29 UTC by Harkishen-Singh

Signed-off-by: Harkishen-Singh <harkishensingh@hotmail.com>

# Description

This PR updates documentation related to Hypershift. On a high-level, the changes include:
1. Arguments are mandatory. Example: `clone`
2. Some configuration options are as flags for `clone`, the rest fall under the configuration file for clone.
3. Configuration field description were given a subheading level where they should have been as headings

# Links

Fixes #[insert issue link, if any]

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs/)

# Review checklists

Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

*   [ ] Is the content technically accurate?
*   [ ] Is the content complete?
*   [ ] Is the content presented in a logical order?
*   [ ] Does the content use appropriate names for features and products?
*   [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

*   [ ] Is the content free from typos?
*   [ ] Does the content use plain English?
*   [ ] Does the content contain clear sections for concepts, tasks, and references?
*   [ ] Have any images been uploaded to the correct location, and are resolvable?
*   [ ] If the page index was updated, are redirects required
      and have they been implemented?
*   [ ] Have you checked the built version of this content?

2023-06-01 02:04 UTC, Loquacity requested changes

2023-06-01 02:04 UTC, Loquacity commented on use-timescale/migration/about-hypershift.md
> +||--parallel|--parallel <NUM_WORKERS>|Number of workers to fetch data parallely from the target database|
```suggestion
||--parallel|--parallel <NUMBER>|Number of workers that can simultaneously fetch data from the target database|
```

2023-06-01 02:04 UTC, Loquacity commented on use-timescale/migration/about-hypershift.md
> +|-c|--config-file|-c <CONFIG_FILE>|Path for advanced hypershift configuration file. For details, please see [hypershift-config]|
```suggestion
|-c|--config-file|-c <PATH>|Path to an advanced hypershift configuration file. For more information, see [hypershift-config]|
```

2023-06-01 02:04 UTC, Loquacity commented on use-timescale/migration/hypershift-config.md
> +# Some constraints like Foreign Keys pointing to a Hypertable cannot be
```suggestion
# Some constraints like foreign keys that point to a hypertable cannot be
```

2023-06-01 02:04 UTC, Loquacity commented on use-timescale/migration/about-hypershift.md
> +Hypershift accepts operations it should perform as commands. These commands should be passed as arguments. Supported commands: `clone`
```suggestion
You can give hypershift commands to perform other operations. 
These commands are passed as arguments. Currently, the only 
supported command is `clone`, which is used to FIXME.
```

I'm not sure if this is right, and it needs a little more exposition.

2023-06-05 09:08 UTC, Harkishen-Singh commented on use-timescale/migration/about-hypershift.md
> +Hypershift accepts operations it should perform as commands. These commands should be passed as arguments. Supported commands: `clone`
The `clone` command in Hypershift is basically an instruction to Hypershift to fork/make a full-copy of the contents of a source database into a target database. I think it was misunderstood.

2023-06-05 23:49 UTC, Loquacity commented on use-timescale/migration/about-hypershift.md
> +Hypershift accepts operations it should perform as commands. These commands should be passed as arguments. Supported commands: `clone`
@Harkishen-Singh Updated for you, let me know what you think.

2023-06-06 02:56 UTC, closed without merging

2023-06-06 05:26 UTC, Loquacity commented
Moved this to a new PR, because the period in the branch name is making the preview build fail.