KBase migration - troubleshooting setup
timescale/docs pull request #253
Opened 2021-08-12 00:32 UTC by Loquacity

# Description

Set up a new troubleshooting page in the Cloud/MST section, and populate with content from https://kb.timescale.cloud/en/articles/3578427-i-received-an-alert-stating-my-database-is-low-on-disk-memory-or-cpu

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes #[insert issue link, if any]

2021-08-12 01:38 UTC, Loquacity commented
![image](https://user-images.githubusercontent.com/3914967/129124978-a760a34d-b248-49db-bad3-d42dd4460cd5.png)

2021-08-18 19:21 UTC, ryanbooz requested changes

2021-08-18 19:21 UTC, ryanbooz commented on timescale-cloud/page-index/page-index.js
> +        href: "troubleshooting-mst",
```suggestion
        href: "troubleshooting",
```

2021-08-18 19:21 UTC, ryanbooz commented on timescale-cloud/troubleshooting-mst.md
> +using your Managed Service for TimescaleDB (MST) account.
```suggestion
using your Timescale Cloud account.
```

2021-08-18 19:21 UTC, ryanbooz commented on timescale-cloud/troubleshooting-mst.md
> +available resources. From the MST Dashboard, select the service that you want to
```suggestion
You can resolve this by logging in to your Timescale Cloud account and increasing your
available resources. From the Timescale Cloud Dashboard, select the service that you want to
```

2021-08-18 19:21 UTC, ryanbooz commented on timescale-cloud/troubleshooting-mst.md
> +[howto-dataretention]: timescaledb/how-to-guides/data-retention
```suggestion
[howto-compression]: /timescaledb/:currentVersion:/how-to-guides/compression
[howto-caggs]: /timescaledb/:currentVersion:/how-to-guides/continuous-aggregates
[howto-dataretention]: /timescaledb/:currentVersion:/how-to-guides/data-retention
```

2021-08-18 20:15 UTC, ryanbooz requested changes

2021-08-18 20:15 UTC, ryanbooz commented on timescale-cloud/troubleshooting.md
> +[howto-dataretention]: timescaledb/how-to-guides/data-retention
```suggestion
[howto-compression]: /timescaledb/:currentVersion:/how-to-guides/compression
[howto-caggs]: /timescaledb/:currentVersion:/how-to-guides/continuous-aggregates
[howto-dataretention]: /timescaledb/:currentVersion:/how-to-guides/data-retention
```

2021-08-24 12:39 UTC, ryanbooz approved these changes

2021-08-24 12:39 UTC, ryanbooz commented on timescale-cloud/troubleshooting.md
> +using your Managed Service for TimescaleDB (MST) account.
```suggestion
using your Timescale Cloud account.
```

2021-08-24 12:39 UTC, ryanbooz commented on timescale-cloud/troubleshooting.md
> +available resources. From the MST Dashboard, select the service that you want to
```suggestion
You can resolve this by logging in to your Timescale Cloud account and increasing your
available resources. From the Timescale Cloud Dashboard, select the service that you want to
```

2021-08-24 14:56 UTC, merged