Fix link
timescale/docs pull request #256
Opened 2021-08-12 11:39 UTC by zseta

2021-08-12 19:06 UTC, ryanbooz approved these changes

2021-08-16 01:25 UTC, Loquacity requested changes

2021-08-16 01:25 UTC, Loquacity commented on api/create_materialized_view.md
> +[real-time-aggregates]:/how-to-guides/continuous-aggregates/real-time-aggregates/
```suggestion
[real-time-aggregates]: /how-to-guides/continuous-aggregates/real-time-aggregates/
```

2021-08-16 01:26 UTC, Loquacity commented on api/create_materialized_view.md
> +[real-time-aggregates]:/how-to-guides/continuous-aggregates/real-time-aggregates/
Looks like they all need it, on second look.

2021-08-16 23:43 UTC, Loquacity approved these changes

2021-08-16 23:44 UTC, merged