add details about pooler auth
timescale/docs pull request #2682
Opened 2023-09-08 20:22 UTC by sebastianwebber

# Description

This PR extends the connection pooler docs, adding details about how to use custom users.

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs/)

# Review checklists

Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

*   [ ] Is the content technically accurate?
*   [ ] Is the content complete?
*   [ ] Is the content presented in a logical order?
*   [ ] Does the content use appropriate names for features and products?
*   [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

*   [ ] Is the content free from typos?
*   [ ] Does the content use plain English?
*   [ ] Does the content contain clear sections for concepts, tasks, and references?
*   [ ] Have any images been uploaded to the correct location, and are resolvable?
*   [ ] If the page index was updated, are redirects required
      and have they been implemented?
*   [ ] Have you checked the built version of this content?

2023-09-11 03:20 UTC, Loquacity commented
Preview is up: https://docs-dev.timescale.com/docs-sebastian-update-pool-user-settings/use-timescale/sebastian-update-pool-user-settings/services/connection-pooling/#user-authentication

2023-09-11 05:11 UTC, Rajakavitha1 requested changes

2023-09-11 05:11 UTC, Rajakavitha1 commented on use-timescale/services/connection-pooling.md
> +configurations for a pooler user, such as `statement_timeout`.
```suggestion
By default, the poolers have authentication to the database, so you can use any
custom users you already have set up without further configuration. You can continue
using the `tsdbadmin` user if that is your preferred method. However, you might need
to add custom configurations for some cases such as `statement_timeout` for a pooler user.
```

2023-09-11 05:11 UTC, Rajakavitha1 commented on use-timescale/services/connection-pooling.md
> +1.  Log in to your database as the `tsdbadmin` user, and create a new role:
```suggestion
1.  Log in to your database as the `tsdbadmin` user, and create a new role named `<MY_APP>` with the password as `<PASSWORD>`:
```

2023-09-11 05:11 UTC, Rajakavitha1 commented on use-timescale/services/connection-pooling.md
> +1.  Alter the role to change the setting for this user. This example changes the
```suggestion
1.  To change the `statement_timeout` settings to 2 seconds for this user:

2023-09-11 05:11 UTC, Rajakavitha1 commented on use-timescale/services/connection-pooling.md
> +   `statement_timeout` to 2 seconds:
```suggestion
   
```

2023-09-11 05:11 UTC, Rajakavitha1 commented on use-timescale/services/connection-pooling.md
> +1.  Connect on the pooler with the new user:
```suggestion
1.  In a new terminal window, connect on the pooler with the new user `<MY_APP>`:
```

2023-09-11 05:11 UTC, Rajakavitha1 commented on use-timescale/services/connection-pooling.md
> +    tsdb=> select current_user;
This is a new step to check if you looked in as '<MY_APP>':

2023-09-11 05:11 UTC, Rajakavitha1 commented on use-timescale/services/connection-pooling.md
> +    tsdb=> show statement_timeout;
This is another step. To check the `statement_timeout` setting soft `<MY_APP>` user:

2023-09-11 05:12 UTC, Rajakavitha1 commented
Thank you for the PR @sebastianwebber . I tested and validated the steps they work as documented. 
```
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 ~ % PGPASSWORD=test123 psql "postgres://my_app@cpda2ec06w.oudd3s6gsr.tsdb.cloud.timescale.com:30080/tsdb?sslmode=require"
psql (14.7 (Homebrew), server 15.4 (Ubuntu 15.4-1.pgdg22.04+1))
WARNING: psql major version 14, server major version 15.
         Some psql features might not work.
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

tsdb=> select current_user;
 current_user 
--------------
 my_app
(1 row)

tsdb=> show statement_timeout;
 statement_timeout 
-------------------
 2s
(1 row)

tsdb=> 
```

2023-09-11 06:40 UTC, Rajakavitha1 approved these changes
LGTM

2023-09-13 13:25 UTC, ggodeke approved these changes
Looks great -- thanks Sebastian!

2023-09-13 13:27 UTC, ggodeke commented
I am not sure how to fix these errors :oh-no:

2023-10-05 13:53 UTC, jonatas commented
Hey @sebastianwebber, looks like we have a error here.

> {"message": "[Google.Units] Put a nonbreaking space between the number and the unit in '2s'.", "location": {"path": "use-timescale/services/connection-pooling.md", "range": {"start": {"line": 91, "column": 7}}}, "severity": "ERROR"}



Probably the change here:

```diff
+    ALTER ROLE my_app SET statement_timeout TO '2s';
```

Probably we should find a way to ignore this case on prose config file.

2023-10-10 00:58 UTC, merged