docs: change wrong param name in time_bucket_gapfill finish param description
timescale/docs pull request #2841
Opened 2023-11-23 08:17 UTC by vonnue-yehya

2023-11-23 08:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/timescale/docs?pullRequest=2841) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/timescale/docs?pullRequest=2841) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/timescale/docs?pullRequest=2841) it.</sub>

2023-11-23 08:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/timescale/docs?pullRequest=2841) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/timescale/docs?pullRequest=2841) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/timescale/docs?pullRequest=2841) it.</sub>

2024-02-15 18:18 UTC, billy-the-fish commented on api/_hyperfunctions/time_bucket_gapfill/time_bucket_gapfill.md
> +          We recommend using a `WHERE` clause rather than specifying `finish`, which is a legacy option.
Best practice is to use the `WHERE` clause. Specifying `finish` is out of date.

2024-02-15 18:18 UTC, billy-the-fish requested changes
Sorry to be annoying :-(.

2024-02-18 14:54 UTC, billy-the-fish commented
@vonnue-yehya, could you sign the CLA please so we can merge your PR.

2024-02-18 14:54 UTC, billy-the-fish approved these changes

2024-02-21 05:56 UTC, vonnue-yehya commented
@billy-the-fish Signed the CLA :)

2024-02-25 12:35 UTC, merged