Add a section about AI/timescale vector
timescale/docs pull request #2862
Opened 2023-11-30 16:15 UTC by cevian

# Description

Add a section for AI / timescale vector

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs/)

# Review checklists

Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

*   [ ] Is the content technically accurate?
*   [ ] Is the content complete?
*   [ ] Is the content presented in a logical order?
*   [ ] Does the content use appropriate names for features and products?
*   [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

*   [ ] Is the content free from typos?
*   [ ] Does the content use plain English?
*   [ ] Does the content contain clear sections for concepts, tasks, and references?
*   [ ] Have any images been uploaded to the correct location, and are resolvable?
*   [ ] If the page index was updated, are redirects required
      and have they been implemented?
*   [ ] Have you checked the built version of this content?

2023-12-04 08:07 UTC, jamessewell approved these changes
Looks good @cevian!

Please note I did not test out the code snippets, have they been double checked?

2023-12-04 15:51 UTC, cevian commented
@jamessewell yes all the code has been at least double-checked :)

2023-12-05 21:48 UTC, jgpruitt requested changes

2023-12-05 21:48 UTC, jgpruitt commented on ai/python-interface.md
> +Next, create the client. This tutorial, uses the sync client. But the library have an async client as well (with an identical interface that
"the library have" should be "the library has"

2023-12-05 21:48 UTC, jgpruitt commented on ai/python-interface.md
> +There are many search options which are be covered below in the
"which are be covered" should be "which are covered"

2023-12-05 22:15 UTC, jamessewell approved these changes
👊

2023-12-06 02:20 UTC, jgpruitt approved these changes

2023-12-06 13:41 UTC, merged