Tested and made revisions to Grafana create dashboard/panel tutorial.
timescale/docs pull request #2982
Opened 2024-02-06 07:09 UTC by jayercule

# Description

* Test tutorials/OLD-grafana/create-dashboard-and-panel.md and rewrote where appropriate
* Updated instructions for new Grafana Cloud UI and took new screenshots
* Made small grammatical/flow edits to text

# Links

Updated images uploaded to shared Ercule/Timescale folder: https://drive.google.com/drive/folders/1UUY8SadUPqg6tP2oyWhMo4HqjX_kxW0S

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs/)

# Review checklists

Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

*   [ ] Is the content technically accurate?
*   [ ] Is the content complete?
*   [ ] Is the content presented in a logical order?
*   [ ] Does the content use appropriate names for features and products?
*   [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

*   [ ] Is the content free from typos?
*   [ ] Does the content use plain English?
*   [ ] Does the content contain clear sections for concepts, tasks, and references?
*   [ ] Have any images been uploaded to the correct location, and are resolvable?
*   [ ] If the page index was updated, are redirects required
      and have they been implemented?
*   [ ] Have you checked the built version of this content?

2024-02-15 18:00 UTC, contentana commented on tutorials/OLD_grafana/create-dashboard-and-panel.md
>  *   [Installed TimescaleDB][install-timescale].
Add instructions to cloud. "installed TimescaleDB or created a Timescale account (with link to sign up)."

2024-02-15 18:06 UTC, contentana requested changes
Hi, Jay! Please add the "create a Timescale account" option at the start.

@jonatas or @jamessewell , can one of you do a technical check on this tutorial? This is one of the bunch we're restoring for the blog! Thanks!

2024-02-20 00:59 UTC, jonatas approved these changes
From the technical perspective nothing changed, and this elements uses very basics of grafana.  Looks good to me but I haven't tested locally.

2024-02-20 14:19 UTC, contentana commented
Thanks, @jonatas ! I really appreciate it.

2024-02-20 14:21 UTC, contentana commented on tutorials/OLD_grafana/create-dashboard-and-panel.md
>  *   [Installed TimescaleDB][install-timescale].
@jayercule, besides adding the cloud info, this is okay. Can you please make those changes, or can I go ahead and make them? I'll then just copy the md file to our blog, as agreed with Justin.

2024-02-29 15:34 UTC, closed without merging