Live migration is more complex than pg_dump/restore
timescale/docs pull request #3030
Opened 2024-02-26 13:39 UTC by JamesGuthrie

# Description

Live migration is more complex than pg_dump/restore

2024-02-26 14:53 UTC, VineethReddy02 requested changes

2024-02-26 14:53 UTC, VineethReddy02 commented on migrate/live-migration/index.md
> +is significantly more complex to execute than a migration with downtime using
The introduction of a Docker image has simplified the process of live migration. The only wrinkle is stopping the CDC once its in sync.

We already have banners in our documentation, stating that live migrations are in an experimental or public preview stage. Thus, I suggest we remove the mention of “significantly complex” as discourages the user to consider this option.

2024-02-26 14:55 UTC, VineethReddy02 commented on migrate/live-migration/index.md
> +is significantly more complex to execute than a migration with downtime using
Perhaps we should eliminate the comparison with dump/restore in terms of ease of use, as the value they provide is completely different. It's an unfair comparison. 🙂

2024-02-27 07:47 UTC, Harkishen-Singh commented on migrate/live-migration/index.md
> +is significantly more complex to execute than a migration with downtime using
How about phrasing it gently as "can require more work to execute than a migration"?

2024-02-27 16:42 UTC, JamesGuthrie commented on migrate/live-migration/index.md
> +is significantly more complex to execute than a migration with downtime using
The reality is that live migration _is_ significantly more complicated than pg_dump/restore. Users should only use it _if they really need to_. IMHO we should be clear about this.

2024-02-27 17:27 UTC, arajkumar approved these changes

2024-02-29 14:23 UTC, VineethReddy02 approved these changes

2024-02-29 14:24 UTC, VineethReddy02 commented on migrate/live-migration/index.md
> +is significantly more complex to execute than a migration with downtime using
I'm not completely convinced, but let's do this.

2024-02-29 14:31 UTC, merged