Update alter_job.md
timescale/docs pull request #3103
Opened 2024-03-28 17:33 UTC by fabriziomello

# Description

[Short summary of why you created this PR]

# Links

Fixes #[insert issue link, if any]

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs/)

# Review checklists

Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

*   [ ] Is the content technically accurate?
*   [ ] Is the content complete?
*   [ ] Is the content presented in a logical order?
*   [ ] Does the content use appropriate names for features and products?
*   [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

*   [ ] Is the content free from typos?
*   [ ] Does the content use plain English?
*   [ ] Does the content contain clear sections for concepts, tasks, and references?
*   [ ] Have any images been uploaded to the correct location, and are resolvable?
*   [ ] If the page index was updated, are redirects required
      and have they been implemented?
*   [ ] Have you checked the built version of this content?

2024-04-03 12:48 UTC, billy-the-fish commented on api/alter_job.md
> +|`fixed_schedule`|`BOOLEAN`|Set to `TRUE` if want to have fixed schedule job runs.|
|`fixed_schedule`|`BOOLEAN`| To enable fixed scheduled job runs, set to `TRUE`.  |
|`initial_start`|[TIMESTAMPTZ](https://www.postgresql.org/docs/current/datatype-datetime.html)| Set the time when the `fixed_schedule` job run starts. For example, `19:10:25-07`|
|`timezone`|`TEXT`| Address the 1-hour shift in start time when clocks change from [Daylight Saving Time to Standard Time](https://en.wikipedia.org/wiki/Daylight_saving_time). For example, `example`.|

Can you check the example value for `initial_start` and  add one for `timezone` please.

2024-04-03 12:49 UTC, billy-the-fish requested changes
Turned the description into an action. Can you check and update the examples please.

2024-04-20 11:37 UTC, jnidzwetzki approved these changes

2024-04-22 14:01 UTC, billy-the-fish approved these changes

2024-04-22 14:05 UTC, merged