feat: naming update.
timescale/docs pull request #3236
Opened 2024-06-07 10:16 UTC by billy-the-fish

# Description

[Short summary of why you created this PR]

# Links

Fixes #[insert issue link, if any]

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs/)

# Review checklists

Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

*   [ ] Is the content technically accurate?
*   [ ] Is the content complete?
*   [ ] Is the content presented in a logical order?
*   [ ] Does the content use appropriate names for features and products?
*   [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

*   [ ] Is the content free from typos?
*   [ ] Does the content use plain English?
*   [ ] Does the content contain clear sections for concepts, tasks, and references?
*   [ ] Have any images been uploaded to the correct location, and are resolvable?
*   [ ] If the page index was updated, are redirects required
      and have they been implemented?
*   [ ] Have you checked the built version of this content?

2024-06-07 16:14 UTC, cevian requested changes, later dismissed

2024-06-07 16:14 UTC, cevian commented on ai/index.md
> +title: Power your AI apps with pgvectorscale
```suggestion
title: Power your AI apps with pgai on Timescale
```

2024-06-07 16:14 UTC, cevian commented on ai/index.md
> +keywords: [ai, vector, pgvector, timescale vector, pgvectorscale]
```suggestion
keywords: [ai, vector, pgvector, pgvectorscale, pgai]
```

2024-06-07 16:14 UTC, cevian commented on ai/index.md
> +# Power your AI apps with pgvectorscale
```suggestion
# Power your AI apps with pgai on Timescale
```

2024-06-07 16:14 UTC, cevian commented on ai/index.md
> +pgvectorscale is PostgreSQL++ for AI applications. With pgvectorscale, you can power production AI applications with PostgreSQL as your vector database, storing both vector embeddings, relational dat
```suggestion
Pgai on Timescale is PostgreSQL++ for AI applications. This suite of tools empowers you to deploy production AI applications with PostgreSQL as your vector database, storing both vector embeddings, relational data (for example, related metadata), and time-based data in the same database.
```

2024-06-07 16:14 UTC, cevian commented on ai/index.md
> +Want to run AI queries from inside your database? [Enable pgai in a Timescale service]
```suggestion
Pgai on Timescale Cloud is comprised of two extensions: pgvectorscale and pgai. Pgvectorscale provides the StreamingDiskANN index to superpower embedding search and make vector queries performant.  Pgai allow you to easily run AI queries from inside the database. Both are installed in your Timescale Cloud instance by default.```

2024-06-07 16:14 UTC, cevian commented on ai/index.md
> +## pgvectorscale vs. pgvector
```suggestion
## pgvectorscale ❤️ pgvector
```

2024-06-07 16:14 UTC, cevian commented on ai/index.md
> +[Pgvector](https://github.com/pgvector/pgvector) is a popular open source extension for vector storage and similarity search in PostgreSQL. Pgvector is packaged as part of pgvectorscale, so you can t
```suggestion
[Pgvector](https://github.com/pgvector/pgvector) is a popular open source extension for vector storage and similarity search in PostgreSQL and [pgvectorscale](https://github.com/timescale/pgvectorscale) adds advanced indexing capabilities to pgvector. Pgai on Timescale offers both extensions so you can use all the capabilities already available in pgvector (like HNSW and ivfflat indexes) and also make use of the StreamingDiskANN index in pgvectorscale to speed up vector search.
```

2024-06-07 16:14 UTC, cevian commented on ai/index.md
> +This makes it easy to migrate your existing pgvector deployment and take advantage of additional features for scale in pgvectorscale. You also have the flexibility to create different index types sui
```suggestion
This makes it easy to migrate your existing pgvector deployment and take advantage of the additional performance features in pgvectorscale. You also have the flexibility to create different index types suited to your needs. See the [vector search indexing][vector-search-indexing] section for more information.
```

2024-06-07 16:14 UTC, cevian commented on ai/index.md
> +pgvectorscale works with the most popular embedding models that have output vectors of 2,000 dimensions or less. Here are some popular choices for text embeddings for use with pgvectorscale:
```suggestion
pgai on Timescale works with the most popular embedding models that have output vectors of 2,000 dimensions or less. Here are some popular choices for text embeddings:
```

2024-06-07 16:14 UTC, cevian commented on ai/key-vector-database-concepts-for-understanding-pgvector.md
> +excerpt: The most important vector database concepts for understanding pgvector and pgvectorscale in PostgreSQL
```suggestion
excerpt: The most important vector database concepts for understanding AI in PostgreSQL: pgvector, pgvectorscale, and pgai
```

2024-06-07 16:14 UTC, cevian commented on ai/key-vector-database-concepts-for-understanding-pgvector.md
> +keywords: [ai, vector, pgvector, timescale vector, pgvectorscale]
```suggestion
keywords: [ai, vector, pgvector, pgvectorscale, pgai]
```

2024-06-07 16:14 UTC, cevian commented on ai/key-vector-database-concepts-for-understanding-pgvector.md
> +There are 3 different indexing algorithms available as part of pgvectorscale: pgvectorscale index, pgvector HNSW, and pgvector ivfflat. The table below illustrates the high-level differences between
```suggestion
There are 3 different indexing algorithms available as part of pgai on Timescale: StreamingDiskANN, HNSW, and ivfflat. The table below illustrates the high-level differences between these algorithms:
```

2024-06-07 16:14 UTC, cevian commented on ai/key-vector-database-concepts-for-understanding-pgvector.md
```suggestion
| StreamingDiskANN | Fast        | Fastest     | No                            |
| HNSW    | Fast     | Fast      | No                            |
| ivfflat | Fastest     | Slowest     | Yes                           |

```

2024-06-07 16:14 UTC, cevian commented on ai/key-vector-database-concepts-for-understanding-pgvector.md
> +For most applications, the pgvectorscale index is recommended.
```suggestion
For most applications, the StreamingDiskANN index is recommended.
```

2024-06-07 16:14 UTC, cevian commented on ai/langchain-integration-for-pgvector-and-timescale-vector.md
> +excerpt: Integrating LangChain with pgvector and pgvectorscale
```suggestion
title: LangChain Integration for pgvector, pgvectorscale, and pgai
excerpt: Integrating LangChain with pgvector, pgvectorscale and pgai
```

2024-06-07 16:14 UTC, cevian commented on ai/langchain-integration-for-pgvector-and-timescale-vector.md
> +keywords: [ai, vector, pgvector, Timescale vector, python, langchain, pgvectorscale]
```suggestion
keywords: [ai, vector, pgvector, python, langchain, pgvectorscale, pgai]
```

2024-06-07 16:14 UTC, cevian commented on ai/langchain-integration-for-pgvector-and-timescale-vector.md
> +# LangChain integration for pgvector and pgvectorscale
```suggestion
# LangChain integration for pgvector, pgvectorscale, and pgai
```

2024-06-07 16:14 UTC, cevian commented on ai/langchain-integration-for-pgvector-and-timescale-vector.md
> +[LangChain](https://www.langchain.com/) is a popular framework for development applications powered by LLMs. pgvectorscale has a native LangChain integration, enabling you to use pgvectorscale as a v
```suggestion
[LangChain](https://www.langchain.com/) is a popular framework for development applications powered by LLMs. pgai on Timescale has a native LangChain integration, enabling you to use it as a vector store and leverage all its capabilities in your applications built with LangChain.
```

2024-06-07 16:14 UTC, cevian commented on ai/langchain-integration-for-pgvector-and-timescale-vector.md
> +Here are resources about using pgvectorscale with LangChain:
```suggestion
Here are resources about using pgai on Timescale with LangChain:
```

2024-06-07 16:14 UTC, cevian commented on ai/langchain-integration-for-pgvector-and-timescale-vector.md
> +- [PostgreSQL Self Querying](https://python.langchain.com/docs/integrations/retrievers/self_query/timescalevector_self_query): Learn how to use pgvectorscale with self-querying in LangChain.
```suggestion
- [Getting started with LangChain and pgvectorscale](https://python.langchain.com/docs/integrations/vectorstores/timescalevector): You'll learn how to use pgai on Timescale for (1) semantic search, (2) time-based vector search, (3) self-querying, and (4) how to create indexes to speed up queries.
- [PostgreSQL Self Querying](https://python.langchain.com/docs/integrations/retrievers/self_query/timescalevector_self_query): Learn how to use pgai on Timescale with self-querying in LangChain.
```

2024-06-07 16:14 UTC, cevian commented on ai/langchain-integration-for-pgvector-and-timescale-vector.md
> +- [Learn more about pgvectorscale and LangChain](https://blog.langchain.dev/timescale-vector-x-langchain-making-postgresql-a-better-vector-database-for-ai-applications/):  A blog post about the uniqu
```suggestion
- [Learn more about pgai on Timescale and LangChain](https://blog.langchain.dev/timescale-vector-x-langchain-making-postgresql-a-better-vector-database-for-ai-applications/):  A blog post about the unique capabilities that pgai on Timescale brings to the LangChain ecosystem.
```

2024-06-07 16:14 UTC, cevian commented on ai/page-index/page-index.js
> +    title: "AI with pgvectorscale",
```suggestion
    title: "AI with pgai on Timescale",
```

2024-06-07 16:14 UTC, cevian commented on ai/page-index/page-index.js
> +      "Information about pgvectorscale and how to use it.",
```suggestion
      "Information about pgai on Timescale and how to use it.",
```

2024-06-07 16:14 UTC, cevian commented on ai/page-index/page-index.js
> +        excerpt: "SQL interface for pgvectorscale and pgvector in PostgreSQL",
```suggestion
        excerpt: "SQL interface for pgai, pgvector and pgvectorscale in PostgreSQL",
```

2024-06-07 16:14 UTC, cevian commented on ai/page-index/page-index.js
> +        excerpt: "Python interface for pgvectorscale and pgvector in PostgreSQL",
```suggestion
        excerpt: "Python interface for pgai, pgvector, and pgvectorscale in PostgreSQL",
```

2024-06-07 16:14 UTC, cevian commented on ai/page-index/page-index.js
> +        excerpt: "Integration of LangChain with pgvectorscale and pgvector",
```suggestion
        excerpt: "Integration of LangChain with pgvector and pgvectorscale",
```

2024-06-07 16:14 UTC, cevian commented on ai/page-index/page-index.js
> +        excerpt: "Integration of LlamaIndex with pgvectorscale and pgvector",
```suggestion
        excerpt: "Integration of LlamaIndex with pgvector and pgvectorscale",
```

2024-06-07 16:14 UTC, cevian commented on ai/pgvectorizer.md
> +title: Embed your PostgreSQL data with pgvectorscale
```suggestion
title: Embed your PostgreSQL data with PgVectorizer
```

2024-06-07 16:14 UTC, cevian commented on ai/pgvectorizer.md
> +excerpt: Create and sync vector embeddings from data in PostgreSQL with pgvectorscale
```suggestion
excerpt: Create and sync vector embeddings from data in PostgreSQL with PgVectorizer
```

2024-06-07 16:14 UTC, cevian commented on ai/pgvectorizer.md
> +tags: [ai, vector, pgvectorscale]
```suggestion
keywords: [ai, vector, pgvector, timescale vector, pgvectorizer]
tags: [ai, vector, pgvectorizer]
```

2024-06-07 16:14 UTC, cevian commented on ai/pgvectorizer.md
> +## Embed PostgreSQL data with pgvectorscale
```suggestion
## Embed PostgreSQL data with PgVectorizer
```

2024-06-07 16:14 UTC, cevian commented on ai/pgvectorizer.md
> +pgvectorscale enables you to create vector embeddings from any data that
```suggestion
PgVectorizer enables you to create vector embeddings from any data that
```

2024-06-07 16:14 UTC, cevian commented on ai/pgvectorizer.md
> +To create vector embeddings, simply attach pgvectorscale to any PostgreSQL
```suggestion
To create vector embeddings, simply attach PgVectorizer to any PostgreSQL
```

2024-06-07 16:14 UTC, cevian commented on ai/pgvectorizer.md
> +embeddings stored in pgvectorscale. For example, say you have a
```suggestion
embeddings stored in PostgreSQL. For example, say you have a
```

2024-06-07 16:14 UTC, cevian commented on ai/pgvectorizer.md
> +from timescale_vector import client, pgvector
```suggestion
from timescale_vector import client, pgvectorizer
```

2024-06-07 16:14 UTC, cevian commented on ai/pgvectorizer.md
> +Now, say you want to embed these blogs in pgvectorscale. First, you
```suggestion
Now, say you want to embed these blogs and store the embeddings in PostgreSQL. First, you
```

2024-06-07 16:14 UTC, cevian commented on ai/pgvectorizer.md
> +vectorizer = pgvector.Vectorize(service_url, 'blog')
```suggestion
vectorizer = pgvectorizer.Vectorize(service_url, 'blog')
```

2024-06-07 16:14 UTC, cevian commented on ai/python-interface-for-pgvector-and-timescale-vector.md
> + Python interface you use to interact with a pgvectorscale service programmatically.
```suggestion
You use pgai on Timescale to power production grade AI applications. `timescale_vector` is the
 Python interface you use to interact with a pgai on Timescale service programmatically.
```

2024-06-07 16:14 UTC, cevian commented on ai/python-interface-for-pgvector-and-timescale-vector.md
> +- [Sign up for pgvectorscale](https://console.cloud.timescale.com/signup?utm_campaign=vectorlaunch&utm_source=docs&utm_medium=direct): Get 90 days free to try pgvectorscale on the Timescale cloud dat
```suggestion
- [Sign up for pgai on Timescale](https://console.cloud.timescale.com/signup?utm_campaign=vectorlaunch&utm_source=docs&utm_medium=direct): Get 90 days free to try pgai on the Timescale cloud data platform. 
```

2024-06-07 16:14 UTC, cevian commented on ai/python-interface-for-pgvector-and-timescale-vector.md
> +Learn how to use pgvectorscale for semantic search on a real-world dataset.
```suggestion
Learn how to use pgai on Timescale for semantic search on a real-world dataset.
```

2024-06-07 16:14 UTC, cevian commented on ai/python-interface-for-pgvector-and-timescale-vector.md
> +If you prefer to use an LLM development or data framework, see pgvectorscale's integrations with [LangChain](https://python.langchain.com/docs/integrations/vectorstores/timescalevector) and [LlamaInd
```suggestion
If you prefer to use an LLM development or data framework, see pgai's integrations with [LangChain](https://python.langchain.com/docs/integrations/vectorstores/timescalevector) and [LlamaIndex](https://gpt-index.readthedocs.io/en/stable/examples/vector_stores/Timescalevector.html).
```

2024-06-07 16:14 UTC, cevian commented on ai/python-interface-for-pgvector-and-timescale-vector.md
> +To interact with pgvectorscale using Python:
```suggestion
To interact with pgai on Timescale using Python:
```

2024-06-07 16:14 UTC, cevian commented on ai/python-interface-for-pgvector-and-timescale-vector.md
> +pgvectorscale index, pgvector HNSW, and pgvector ivfflat.
```suggestion
StreamingDiskANN, HNSW, and ivfflat.
```

2024-06-07 16:14 UTC, cevian commented on ai/python-interface-for-pgvector-and-timescale-vector.md
>  | pgvector ivfflat | Fastest     | Slowest     | Yes                           |
```suggestion
| StreamingDiskAnn | Fast        | Fastest     | No                            |
| HNSW    | Fast   | Faster      | No                            |
| ivfflat | Fastest     | Slowest     | Yes                           |
```

2024-06-07 16:14 UTC, cevian commented on ai/python-interface-for-pgvector-and-timescale-vector.md
> +You should use the pgvectorscale index for most use cases. This
```suggestion
You should use the StreamingDiskANN index for most use cases. This
```

2024-06-07 16:14 UTC, cevian commented on ai/python-interface-for-pgvector-and-timescale-vector.md
> +#### pgvectorscale index
```suggestion
#### StreamingDiskANN index
```

2024-06-07 16:14 UTC, cevian commented on ai/python-interface-for-pgvector-and-timescale-vector.md
> +The pgvectorscale index is a graph-based algorithm that uses the
```suggestion
The StreamingDiskANN index is a graph-based algorithm that uses the
```

2024-06-07 16:14 UTC, cevian commented on ai/python-interface-for-pgvector-and-timescale-vector.md
> +Note that the pgvectorscale index only supports cosine distance at
```suggestion
Note that the StreamingDiskANN index only supports cosine distance at
```

2024-06-07 16:14 UTC, cevian commented on ai/sql-interface-for-pgvector-and-timescale-vector.md
> +Nevertheless, there are excellent approximate algorithms. There are 3 different indexing algorithms available on the Timescale platform: pgvectorscale Index, pgvector HNSW, and pgvector ivfflat. Belo
```suggestion
Nevertheless, there are excellent approximate algorithms. There are 3 different indexing algorithms available on the Timescale platform: StreamingDiskANN, HNSW, and ivfflat. Below is the trade-offs between these algorithms:
```

2024-06-07 16:14 UTC, cevian commented on ai/sql-interface-for-pgvector-and-timescale-vector.md
>  | pgvector ivfflat | Fastest     | Slowest     | Yes                           |
```suggestion
| StreamingDiskANN | Fast        | Fastest     | No                            |
| HNSW    | Fast     | Fast      | No                            |
| ivfflat | Fastest     | Slowest     | Yes                           |
```

2024-06-07 16:14 UTC, cevian commented on ai/sql-interface-for-pgvector-and-timescale-vector.md
> +For most use cases, the pgvectorscale index is recommended.
```suggestion
For most use cases, the StreamingDiskANN index is recommended.
```

2024-06-07 16:14 UTC, cevian commented on ai/sql-interface-for-pgvector-and-timescale-vector.md
> +### pgvectorscale index
```suggestion
### StreamingDiskANN index
```

2024-06-07 16:14 UTC, cevian commented on ai/sql-interface-for-pgvector-and-timescale-vector.md
> +The pgvectorscale index is a graph-based algorithm that uses the [DiskANN](https://github.com/microsoft/DiskANN) algorithm. You can read more about it on the [blog](https://www.timescale.com/blog/how
```suggestion
The StreamingDiskANN index is a graph-based algorithm that was inspired by the [DiskANN](https://github.com/microsoft/DiskANN) algorithm. You can read more about it on the [blog](https://www.timescale.com/blog/how-we-made-postgresql-the-best-vector-database/) announcing its release.
```

2024-06-07 16:14 UTC, cevian commented on ai/sql-interface-for-pgvector-and-timescale-vector.md
> +The pgvectorscale index is a graph-based algorithm that uses the [DiskANN](https://github.com/microsoft/DiskANN) algorithm. You can read more about it on the [blog](https://www.timescale.com/blog/how
will need to change the blog link after new blog is out

2024-06-07 16:14 UTC, cevian commented on ai/sql-interface-for-pgvector-and-timescale-vector.md
> +pgvectorscale indexes only support cosine distance at this time, so you should use the `<=>` operator in your queries.
```suggestion
StreamingDiskANN indexes only support cosine distance at this time, so you should use the `<=>` operator in your queries.
```

2024-06-07 16:14 UTC, cevian commented on ai/sql-interface-for-pgvector-and-timescale-vector.md
> +#### pgvectorscale index build-time parameters
```suggestion
#### StreamingDiskANN index build-time parameters
```

2024-06-07 16:14 UTC, cevian commented on ai/sql-interface-for-pgvector-and-timescale-vector.md
> +#### pgvectorscale query-time parameters
```suggestion
#### StreamingDiskANN query-time parameters
```

2024-06-07 16:14 UTC, cevian commented on ai/sql-interface-for-pgvector-and-timescale-vector.md
> +#### pgvectorscale index-supported queries
```suggestion
#### StreamingDiskANN index-supported queries
```

2024-06-10 15:22 UTC, jgpruitt requested changes

2024-06-10 15:22 UTC, jgpruitt commented on ai/index.md
>  - [Sentence transformers](https://huggingface.co/sentence-transformers): Several popular open source models for embedding generation from text.
pgai does not support Sentence Transformers from Huggingface yet.

2024-06-10 15:49 UTC, billy-the-fish commented on ai/index.md
>  - [Sentence transformers](https://huggingface.co/sentence-transformers): Several popular open source models for embedding generation from text.
Removed.

2024-06-10 16:25 UTC, jgpruitt approved these changes

2024-06-10 16:27 UTC, billy-the-fish commented on ai/sql-interface-for-pgvector-and-timescale-vector.md
> +The pgvectorscale index is a graph-based algorithm that uses the [DiskANN](https://github.com/microsoft/DiskANN) algorithm. You can read more about it on the [blog](https://www.timescale.com/blog/how
Done, but to be tested.

2024-06-10 20:35 UTC, avthars requested changes
Left suggestions, otherwise super!

2024-06-10 20:35 UTC, avthars commented on ai/index.md
> +Pgai on Timescale Cloud is comprised of two extensions: pgvectorscale and pgai. Pgvectorscale provides the StreamingDiskANN index to superpower embedding search and make vector queries performant.  P
```suggestion
Pgai on Timescale Cloud is comprised of three extensions: pgvector, pgvectorscale and pgai. pgvector provides the vector data type and HNSW search index. Pgvectorscale provides the StreamingDiskANN index to superpower embedding search and make vector queries performant.  Pgai allows you to easily call AI embedding and generation models from inside the database. All three extensions are installed in your Timescale Cloud instance by default.```
```

2024-06-10 20:35 UTC, avthars commented on ai/index.md
> +<Highlight type="cloud" header="Try out pgvectorscale" button="Try for free">
```suggestion
<Highlight type="cloud" header="Start building today" button="Try for free">
```

2024-06-10 20:35 UTC, avthars commented on ai/page-index/page-index.js
> +    title: "AI with pgai on Timescale",
```suggestion
    title: "AI  and Vector: pgai on Timescale",
```

2024-06-10 20:35 UTC, avthars commented on ai/index.md
> +title: Power your AI apps with pgai on Timescale
```suggestion
title: Power your AI apps with PostgreSQL
```

2024-06-10 20:35 UTC, avthars commented on ai/index.md
> +Pgai on Timescale is PostgreSQL++ for AI applications. This suite of tools empowers you to deploy production AI applications with PostgreSQL as your vector database, storing both vector embeddings, r
```suggestion
Pgai on Timescale is a cloud solution for building search, RAG, and AI agents with PostgreSQL. This suite of tools empowers you to deploy production AI applications with PostgreSQL as your vector database, storing both vector embeddings, relational data (for example, related metadata), and time-based data in the same database.
```

2024-06-10 20:59 UTC, avthars approved these changes
Onward

2024-06-11 09:01 UTC, merged