Add TimescaleDB with AWS Lambda tutorial
timescale/docs pull request #325
Opened 2021-08-31 11:53 UTC by zseta

# Description

Adding the TimescaleDB with AWS Lambda tutorial.

2021-09-01 01:11 UTC, Loquacity commented on timescaledb/tutorials/page-index/page-index.js
> +        href: 'aws-lambda',
```suggestion
        href: 'aws-lambda',
        excerpt: 'Tutorial for using TimescaleDB with AWS Lambda'
```

2021-09-01 03:19 UTC, Loquacity requested changes
Only reviewed the first file, will get back to the second later on.

2021-09-01 03:19 UTC, Loquacity commented on timescaledb/tutorials/aws-lambda/3rd-party-api-ingest.md
> +Then use the `events put-target` command.
```suggestion
When you have finished, use the `events put-target` command to .... <FIXME>
```

2021-09-01 03:19 UTC, Loquacity commented on timescaledb/tutorials/aws-lambda/3rd-party-api-ingest.md
> +To check if the rule is connected to the Lambda function, go to AWS console > Amazon EventBridge > Events > Rules,
```suggestion
To check if the rule is connected to the Lambda function, in the AWS console, navigate to Amazon EventBridge > Events > Rules, and
```

2021-09-01 03:19 UTC, Loquacity commented on timescaledb/tutorials/aws-lambda/3rd-party-api-ingest.md
> +To check if the rule is connected to the Lambda function, go to AWS console > Amazon EventBridge > Events > Rules,
Can probably use a proper right arrow here, too, but that's non-blocking.

2021-09-01 03:19 UTC, Loquacity commented on timescaledb/tutorials/aws-lambda/3rd-party-api-ingest.md
> +select your rule and the Lambda function’s name should be under “Target(s)”.
```suggestion
select your rule. The Lambda function’s name is listed under `Target(s)`.
```

2021-09-01 09:58 UTC, zseta commented on timescaledb/tutorials/aws-lambda/3rd-party-api-ingest.md
> +Dockerfile:
@Loquacity you mean this whole file, or just the Dockerfile step?

2021-09-01 10:21 UTC, zseta commented on timescaledb/tutorials/aws-lambda/create-data-api.md
> +do directly in a Lambda function. A workaround to this issue is to download the [compiled version of the library](https://github.com/jkehler/awslambda-psycopg2) and upload it as a Lambda Layer.
https://github.com/timescale/docs/pull/325/commits/c3163bb87acb5aae7dcc2f8237764dd44d5afbd7

2021-09-01 10:27 UTC, zseta commented on timescaledb/tutorials/aws-lambda/create-data-api.md
> +Now your function code is uploaded along with the database connection details. Let's see if it retrieves the data we expect!
the "## Upload the function in AWS Lambda" section uploads the function code.
the "## Add database configuration to AWS Lambda" section uploads the environment variables
both uses the command line tool
the `config = {...}` code is already part of the whole function code that was uploaded previously

2021-09-01 10:28 UTC, zseta commented on timescaledb/tutorials/aws-lambda/3rd-party-api-ingest.md
> +Then use the `events put-target` command.
https://github.com/timescale/docs/pull/325/commits/6cdfc2d4613581a6d4e9de396f8f812068116c5b

2021-09-01 10:30 UTC, zseta commented on timescaledb/tutorials/aws-lambda/3rd-party-api-ingest.md
> +larger than the 250MB limit of Lambda. In this case, you might want to read about. With a Docker container, your
Right, fixed here https://github.com/timescale/docs/pull/325/commits/d87885bad7bc90e6aea287055f83da469694b81c#

2021-09-01 23:22 UTC, ryanbooz approved these changes

2021-09-02 13:09 UTC, zseta commented on timescaledb/tutorials/aws-lambda/create-data-api.md
> +Now your function code is uploaded along with the database connection details. Let's see if it retrieves the data we expect!
No actually you are 100% right (just realizing now) here's a fix https://github.com/timescale/docs/pull/325/commits/dffa40e43103ee9831586345556dec1f5da11c4c and https://github.com/timescale/docs/pull/325/commits/56ba19d880c7a637f925985f0c6e34b6be60dc08 https://github.com/timescale/docs/pull/325/commits/b5533191032bff9320b88c999af4b5028ada1744 @ryanbooz

2021-09-02 13:20 UTC, merged

2021-09-03 04:56 UTC, Loquacity commented
> I'm fine for you to merge if/when you clarify my question. The process/procedure stuff might be a larger conversation that we all need training on. So, I think it's OK as it is now, but definitely want to go back and help this fall into line with the larger standards that Lana is working through.

Yes, I'll make a note to go back over this section and rework it next week.