Billing groups info added to MST billing page
timescale/docs pull request #3383
Opened 2024-08-19 08:55 UTC by atovpeko

# Description

[Short summary of why you created this PR]

# Links

Fixes #[insert issue link, if any]

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs/)

# Review checklists

Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

*   [ ] Is the content technically accurate?
*   [ ] Is the content complete?
*   [ ] Is the content presented in a logical order?
*   [ ] Does the content use appropriate names for features and products?
*   [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

*   [ ] Is the content free from typos?
*   [ ] Does the content use plain English?
*   [ ] Does the content contain clear sections for concepts, tasks, and references?
*   [ ] Have any images been uploaded to the correct location, and are resolvable?
*   [ ] If the page index was updated, are redirects required
      and have they been implemented?
*   [ ] Have you checked the built version of this content?

2024-08-19 09:12 UTC, billy-the-fish requested changes
Good work, nearly there.

2024-08-19 09:12 UTC, billy-the-fish commented on mst/billing.md
> +To access billing groups in the [Aiven Console][aiven-console], you must be a
Careful here, you are using MST not Aiven:

https://portal.managed.timescale.com/account/a4bf28029b59/billing/overview

Billing groups are in:

https://portal.managed.timescale.com/account/a4bf28029b59/billing/billing-groups

2024-08-19 09:12 UTC, billy-the-fish commented on mst/billing.md
> +1. In the organization, click **Billing** > **Create billing group**.
In [MST Console][link to console], click **Billing** > ...

2024-08-19 09:12 UTC, billy-the-fish commented on mst/billing.md
> +1. Enter the billing details. You can copy these details from another
Put the second sentence on a newline so it is under the action please.

2024-08-19 09:12 UTC, billy-the-fish commented on mst/billing.md
> +1. Select the projects to add to this billing group. You can skip this step and
Same here, newline for the explanation bit.

2024-08-19 09:12 UTC, billy-the-fish commented on mst/billing.md
> +    1. Find the billing group to rename and click **Actions > Rename**.
In [MST Console][link to console], bla bla

2024-08-19 09:12 UTC, billy-the-fish commented on mst/billing.md
> +    1. Select the name of the billing group to update.
In [MST Console][link to console], click **Billing** > ...  bla bla

2024-08-19 09:12 UTC, billy-the-fish commented on mst/billing.md
> +    1. Select the name of the billing group to delete.
In [MST Console][link to console], click **Billing** > ...  bla bla

2024-08-19 09:12 UTC, billy-the-fish commented on mst/billing.md
> +  1. Go to **Billing > Billing groups**.
In [MST Console][link to console], click **Billing** > ...  bla bla

2024-08-19 09:12 UTC, billy-the-fish commented on mst/billing.md
> +  1. Select the name of the billing group.
In [MST Console][link to console], click **Billing** > ...  bla bla

2024-08-19 13:11 UTC, billy-the-fish approved these changes
LGTM. Good doc.

2024-08-20 14:51 UTC, merged

2024-08-27 17:57 UTC, ashegrud commented
Hi @atovpeko and @billy-the-fish  , apologies for the late addition here.   

 I need to reopen this as we need to update 1 item from the docs.  Billing > Corporate billing .  It should say  Payment terms for corporate invoices are **14 days net**  .  Instead of Payment terms for corporate invoices are **10 days net**