chore: update user management page.
timescale/docs pull request #3485
Opened 2024-10-07 11:55 UTC by billy-the-fish

2024-10-09 07:20 UTC, atovpeko requested changes
Can we align to only use bold for UI elements, not code font? To quote the style guide: When referring to any UI element by name, put its name in bold, using the b element in HTML or ** in Markdown. This includes names for buttons, menus, dialogs, windows, list items, or any other feature on the page that has a visible name. Don't use code font for UI elements, unless it's an element that meets the [requirements for code font](https://developers.google.com/style/code-in-text). In that case, use both code font and bold

2024-10-09 07:20 UTC, atovpeko commented on use-timescale/members.md
> +When you sign up for a [30 day free trial][sign-up], $CLOUD_LONG creates a project for you, and
```suggestion
When you sign up for a [30-day free trial][sign-up], $CLOUD_LONG creates a project for you, and
```

2024-10-09 07:20 UTC, atovpeko commented on use-timescale/members.md
> +to add and delete users, edit project settings and transfer the owner role to another user. When you transfer
```suggestion
add and delete users, edit project settings, and transfer the owner role to another user. When you transfer
```

2024-10-09 07:20 UTC, atovpeko commented on use-timescale/members.md
> +1.  Next to the person you want to remove, click `⋮`, then click the trash can.
```suggestion
1.  Next to the person you want to remove, click `⋮`, then click the trash can icon.
```

2024-10-09 11:56 UTC, mwarejohn approved these changes
Enterprise user section is okay

2024-10-09 12:52 UTC, syvb commented on use-timescale/members.md
> +     $CLOUD_LONG opens and you are added to the project.
SAML users aren't automatically added to the project; they need to accept the invite from the notification bell.

2024-10-09 12:56 UTC, billy-the-fish commented on use-timescale/members.md
> +     $CLOUD_LONG opens and you are added to the project.
Hi @syvb , thanks for the comment. I'm afraid I don't know what the notification bell is. Can you tell me what the workflow for SAML users is please (Do they have to be enterprise users?). For example:

1. User is invited to a project by the Owner or another project member, then: 
    - Existing user: do this
    - New user: do that

2024-10-09 16:15 UTC, syvb commented on use-timescale/members.md
> +     $CLOUD_LONG opens and you are added to the project.
This is the notification bell:
<img width="659" alt="image" src="https://github.com/user-attachments/assets/b3cb1d62-4185-4d76-ace4-79d7f9e08b02">

Normally customers have to be on the Enterprise tier for us to enable SAML for them, but we can make exceptions if needed. How the flow works for SAML users is:

1. Invitee is invited to the project by another project member
2. Invitee logs in to the Timescale console through their company's identity provider.
3. Invitee clicks the notification bell in the bottom left (which used to be in the top right before the recent console redesign)
4. Invitee clicks the button to accept the invite
5. Invitee uses the project switcher in the top left to switch between the project they were just invited to and their default project

2024-10-11 08:49 UTC, billy-the-fish commented on use-timescale/members.md
> +     $CLOUD_LONG opens and you are added to the project.
Thanks for the guidance, that really helped. I have updated the docs.

2024-10-14 14:38 UTC, syvb approved these changes

2024-10-14 15:54 UTC, atovpeko approved these changes

2024-10-14 16:01 UTC, merged