Add an intro about account/service/connection
timescale/docs pull request #3490
Opened 2024-10-08 07:57 UTC by atovpeko

2024-10-08 08:13 UTC, billy-the-fish requested changes

2024-10-08 08:13 UTC, billy-the-fish commented on getting-started/services.md
> +1. Create a Timescale service, that is, a PostgreSQL database instance, in Timescale Console.
```suggestion
1. Create a $SERVICE_LONG: a PostgreSQL database instance powered by [$TIMESCALE_DB](https://docs.timescale.com/#TimescaleDB), built for production, and extended with cloud features like transparent data tiering to object storage.
```

2024-10-08 08:13 UTC, billy-the-fish commented on getting-started/services.md
> +1. Create a Timescale account: register in Timescale Console to get a centralized point for your database management.
```suggestion
1. Create a$COMPANY account: register in  $CONSOLE to get a centralized point to administer and interact with your data.
```

2024-10-08 08:13 UTC, billy-the-fish commented on getting-started/services.md
> +This page takes you through those steps. It also explains how to create a standard PostgreSQL table in your service and convert it into a [hypertable][hypertables]. Anything you can do with regular P
Change this to a step

2024-10-08 08:13 UTC, billy-the-fish commented on getting-started/services.md
> +
And add an intro sentence infront of every procedure to give a longer explanation of what it is all about.

2024-10-21 18:17 UTC, billy-the-fish commented on getting-started/services.md
>  - **Dynamic PostgreSQL**: for all other workloads. A PostgreSQL instance with a
```suggestion
- **PostgreSQL**: for all other workloads. A PostgreSQL instance with a 
```

Please swap the order so it matches.

2024-10-29 07:45 UTC, jamessewell commented on getting-started/services.md
> +1. [Create a hypertable][create-a-hypertable]: create a standard PostgreSQL table in your service, the convert it into a [hypertable][hypertables].
the convert -> then convert

2024-10-29 07:45 UTC, jamessewell commented on getting-started/services.md
> +1. [Create a $COMPANY account][creatre-an-account]: register in $CONSOLE to get a centralized point to administer and interact with your data.
Show creatre be create? I know it's not visible 😅

2024-11-14 14:57 UTC, billy-the-fish approved these changes

2024-11-19 12:29 UTC, merged