Timestamp vs timestamptz explanation
timescale/docs pull request #3491
Opened 2024-10-08 09:41 UTC by atovpeko

2024-10-08 11:47 UTC, mkindahl approved these changes

2024-10-08 11:47 UTC, mkindahl commented on use-timescale/hypertables/create.md
> +use `timestamptz` instead. For why the use of `timestamp` is discouraged, see [PostgreSQL timestamp][postgresql-timestamp].
It is possible to use integers as well for partitioning, even though they do not represent a time. This is not normally what we recommend though.

```suggestion
Hypertables are designed for real-time analytics and typically partitioned by columns that hold time values. These can be of the `timestamptz`, `date`, or `integer` types. While `timestamp` is also supported, a best practice is to 
use `timestamptz` instead. For why the use of `timestamp` is discouraged, see [PostgreSQL timestamp][postgresql-timestamp].
```

2024-10-08 11:51 UTC, billy-the-fish requested changes

2024-10-08 11:51 UTC, billy-the-fish commented on api/dimension_info.md
> +  While both `timestamp` and `timestamptz` data types are supported for partitioning columns, a best practice is to use `timestamptz`. For why the use of `timestamp` is discouraged, see [PostgreSQL t
```suggestion
  While both `timestamp` and `timestamptz` data types are supported for partitioning columns, best practice is to use `timestamptz`. [PostgreSQL timestamp(https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_timestamp_.28without_time_zone.29) explains why using `timestamp` is discouraged.
```

2024-10-08 11:51 UTC, billy-the-fish commented on use-timescale/hypertables/create.md
> +Hypertables are designed for real-time analytics and partitioned by columns that hold time values. These can be of the `timestamptz`, `date`, or `integer` types. While `timestamp` is also supported,
```suggestion
Hypertables are designed for real-time analytics and partitioned by columns that hold time values. These can be of the `timestamptz`, `date`, or `integer` types. While `timestamp` is also supported, best practice is to 
```

2024-10-08 11:51 UTC, billy-the-fish commented on use-timescale/hypertables/create.md
> +use `timestamptz` instead. For why the use of `timestamp` is discouraged, see [PostgreSQL timestamp][postgresql-timestamp].
```suggestion
use `timestamptz` instead. [PostgreSQL timestamp(https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_timestamp_.28without_time_zone.29) explains why using `timestamp` is discouraged.
```

2024-10-09 07:48 UTC, billy-the-fish approved these changes
LGTM

2024-10-09 07:59 UTC, merged