I/O boost docs
timescale/docs pull request #3610
Opened 2024-11-21 12:00 UTC by atovpeko

2024-11-21 13:35 UTC, billy-the-fish requested changes
Sorry, last minute thought from me.

2024-11-21 13:35 UTC, billy-the-fish commented on use-timescale/services/i-o-boost.md
> +I/O boost allows you to increase I/O and throughput of a service's EBS storage on the need-only basis. This means you can enable it for the most demanding applications, while keeping costs under cont
```suggestion
You use I/O boost to increase I/O and throughput of a service's high-performance storage on the need-only basis. This means you can enable it for the most demanding applications, while keeping costs under control. 
```
Add a link to https://docs.timescale.com/use-timescale/latest/data-tiering/.

2024-11-21 13:35 UTC, billy-the-fish commented on use-timescale/services/i-o-boost.md
> +---
@esclymeTS ,  I have had a bit of a think about this. Would it be best to add this page to the https://docs.timescale.com/use-timescale/latest/data-tiering/ section and add links to it from the main page.

2024-11-25 14:47 UTC, esclymeTS approved these changes

2024-11-25 15:08 UTC, billy-the-fish commented on use-timescale/services/i-o-boost.md
> +You use I/O boost to increase I/O and throughput of a service's [high-performance storage][data-tiering] on the need-only basis. This means you can enable it for the most demanding applications, whil
```suggestion
You use I/O boost to increase I/O and throughput of a service's [high-performance storage][data-tiering]. This means you can enable it for the most demanding applications, while keeping costs under control.
```

2024-11-25 15:08 UTC, billy-the-fish commented on use-timescale/services/i-o-boost.md
> +Enabling I/O boost increases I/O to 16,000 IOPS and throughput to 1,000 MBps. The boost also applies to any [high-availability][ha-replicas] or [read replicas][read-replicas] you might have running f
```suggestion
Enabling I/O boost increases I/O to 16,000 IOPS and throughput to 1,000 MBps. The boost also applies to any [high-availability][ha-replicas] replicas you might have running for a service, although for an additional fee. 
```

2024-11-25 18:19 UTC, billy-the-fish approved these changes
LGTM.

2024-11-26 08:09 UTC, merged