3579 feedback page self hostedlatestupgradesminor upgrade
timescale/docs pull request #3630
Opened 2024-11-29 16:07 UTC by billy-the-fish

Update the upgrade instructions so users no longer have the same issue as https://github.com/timescale/docs/issues/3579.

2024-11-29 16:58 UTC, graveland approved these changes
lgtm, added a few comments though, nothing major

2024-11-29 16:58 UTC, graveland commented on _partials/_migrate_self_postgres_implement_migration_path.md
> +1. **Check that you have upgraded to the correct version TimescaleDB**
```suggestion
1. **Check that you have upgraded to the correct version of TimescaleDB**
```

2024-11-29 16:58 UTC, graveland commented on _partials/_plan_upgrade.md
> +* You might need to
Duplicate "You might need to"

2024-11-29 16:58 UTC, graveland commented on self-hosted/upgrades/major-upgrade.md
> +  intrusive operation. In case of disaster, [create a database backup][backup], and ensure that the backup
Maybe?

```suggestion
  intrusive operation. To protect against disasters, [create a database backup][backup], and ensure that the backup
```

2024-11-29 16:58 UTC, graveland commented on self-hosted/upgrades/minor-upgrade.md
> +# Upgrade TimescaleDB to a minor version
```suggestion
# Upgrade TimescaleDB to a new minor version
```

2024-11-29 16:58 UTC, graveland commented on self-hosted/upgrades/minor-upgrade.md
> +    intrusive operation. In case of disaster, [create a database backup][backup], and ensure that the backup
(same as the other related comment)

2024-11-29 16:58 UTC, graveland commented on self-hosted/upgrades/upgrade-pg.md
> +  intrusive operation. In case of disaster, [create a database backup][backup], and ensure that the backup
(same)

2024-12-02 09:57 UTC, billy-the-fish commented on _partials/_plan_upgrade.md
> +* You might need to
Nice spot, fixed.

2024-12-02 09:57 UTC, billy-the-fish commented on self-hosted/upgrades/minor-upgrade.md
> +    intrusive operation. In case of disaster, [create a database backup][backup], and ensure that the backup
Fixed.

2024-12-02 09:58 UTC, billy-the-fish commented on self-hosted/upgrades/upgrade-pg.md
> +  intrusive operation. In case of disaster, [create a database backup][backup], and ensure that the backup
Fixed.

2024-12-02 12:39 UTC, atovpeko requested changes
A few minor things

2024-12-02 12:39 UTC, atovpeko commented on _partials/_plan_upgrade.md
> +*   Check the version TimescaleDB you are currently running, and the version you want to upgrade to
```suggestion
*   Check the version of TimescaleDB you are currently running, and the version you want to upgrade to
```

2024-12-02 12:39 UTC, atovpeko commented on self-hosted/upgrades/downgrade.md
> +1. **Check that you have downgraded to the correct version TimescaleDB**
```suggestion
1. **Check that you have downgraded to the correct version of TimescaleDB**
```

2024-12-02 12:39 UTC, atovpeko commented on self-hosted/upgrades/major-upgrade.md
> +This page shows you how to perform a major upgrade, for minor upgrades, see
```suggestion
This page shows you how to perform a major upgrade. For minor upgrades, see
```

2024-12-02 12:39 UTC, atovpeko commented on self-hosted/upgrades/major-upgrade.md
> +When you upgrade from TimescaleDB 1, to TimescaleDB 2, scripts
```suggestion
When you upgrade from TimescaleDB 1 to TimescaleDB 2, scripts
```

2024-12-02 12:39 UTC, atovpeko commented on self-hosted/upgrades/minor-upgrade.md
> +A minor upgrade is when you update from TimescaleDB `<major version>.x`, to TimescaleDB `<major version>.y`.
```suggestion
A minor upgrade is when you update from TimescaleDB `<major version>.x` to TimescaleDB `<major version>.y`. 
```

2024-12-02 12:39 UTC, atovpeko commented on self-hosted/upgrades/upgrade-pg.md
> +TimescaleDB is a PostgreSQL extension. When you upgrade, ensure that you are installing to compatible versions of
the compatible versions?

2024-12-02 12:39 UTC, atovpeko commented on self-hosted/upgrades/upgrade-pg.md
> +   This variables hold the connection information for the database to upgrade:
```suggestion
   This variable holds the connection information for the database to upgrade:
```

2024-12-02 13:26 UTC, billy-the-fish commented on _partials/_plan_upgrade.md
> +*   Check the version TimescaleDB you are currently running, and the version you want to upgrade to
Removed

2024-12-02 13:33 UTC, billy-the-fish commented on self-hosted/upgrades/upgrade-pg.md
> +TimescaleDB is a PostgreSQL extension. When you upgrade, ensure that you are installing to compatible versions of
Updated.

2024-12-02 14:10 UTC, atovpeko approved these changes

2024-12-03 12:19 UTC, merged