time_bucket_ng() - document time zones support
timescale/docs pull request #383
Opened 2021-09-13 12:43 UTC by afiskon

# Description

Document the fact that time_bucket_ng() supports time zones.

# Version

Which documentation version does this PR apply to?

- [ ] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

None

2021-09-13 23:04 UTC, Loquacity requested changes

2021-09-13 23:04 UTC, Loquacity commented on api/time_bucket_ng.md
> +by months in specified timezone:
```suggestion
This example shows how `time_bucket_ng()` is used to bucket data
by months in a specified timezone:
```

2021-09-14 02:02 UTC, gayyappan requested changes

2021-09-14 07:33 UTC, afiskon commented on api/time_bucket_ng.md
> +The following example shows how `time_bucket_ng()` can be used to bucket data
👍

2021-09-14 13:12 UTC, gayyappan approved these changes
minor change requested.

2021-09-14 13:12 UTC, gayyappan commented on api/time_bucket_ng.md
> +`time_bucket` works only with small units of time, the `time_bucket_ng()`
```suggestion
`time_bucket` works only with small units of time,  `time_bucket_ng()` 
```

2021-09-14 13:45 UTC, afiskon commented
> minor change requested.

Merged, thanks!

2021-09-14 13:46 UTC, merged