Port content from legacy website
timescale/docs pull request #56
Opened 2021-05-14 19:31 UTC by jonatas

# Description

[Short summary of why you created this PR]

# Version

Which documentation version does this PR apply to?

- [ ] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes #[insert issue link, if any]

2021-05-17 00:30 UTC, Loquacity requested changes
Just some small edits.

2021-05-17 00:30 UTC, Loquacity commented on api/run_job.md
> +Any background worker job can be run in foreground when executed with
```suggestion
Any background worker job can be run in the foreground when executed with
```

2021-05-17 00:30 UTC, Loquacity commented on api/run_job.md
> +log level.
```suggestion
`run_job`. You can use this with an increased log level to help debug problems.
```

2021-05-17 00:30 UTC, Loquacity commented on api/run_job.md
> +|`job_id`| (INTEGER)  TimescaleDB background job id |
```suggestion
|`job_id`| (INTEGER)  TimescaleDB background job ID |
```

2021-05-17 00:30 UTC, Loquacity commented on api/run_job.md
> +Set log level shown to client to `DEBUG1` and run the job with the job id 1000.
```suggestion
Set log level shown to client to `DEBUG1` and run the job with the job ID 1000.
```

2021-05-17 11:19 UTC, jonatas commented
Thanks for the suggestions @Loquacity!

2021-05-17 11:25 UTC, jonatas commented
@Loquacity I enabled auto-merge for this PR after addressing the changes. Thank you for the suggestions! I'm learning from them!

2021-05-18 00:54 UTC, Loquacity approved these changes

2021-05-18 00:54 UTC, merged