Document triggers on distributed hypertables
timescale/docs pull request #595
Opened 2021-11-12 15:41 UTC by erimatnor

Add a subsection on triggers to the distributed hypertables
section. Explain the different behavior of triggers on distributed
hypertables compared to regular hypertables.

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)

2021-11-12 15:52 UTC, NunoFilipeSantos approved these changes
LGTM. Thank you for the quick PR.

2021-11-15 02:25 UTC, Loquacity requested changes

2021-11-15 02:25 UTC, Loquacity commented on timescaledb/how-to-guides/hypertables/distributed-hypertables.md
> +(see below). However, this optimized plan won't work if the `INSERT`
```suggestion
However, this optimized plan won't work if the `INSERT`
```

2021-11-15 02:25 UTC, Loquacity commented on timescaledb/how-to-guides/hypertables/distributed-hypertables.md
> +statement has a `RETURNING` clause and the distributed hypertable has
```suggestion
statement has a `RETURNING` clause, and the distributed hypertable has
```

2021-11-15 02:25 UTC, Loquacity commented on timescaledb/how-to-guides/hypertables/distributed-hypertables.md
> +node picks.
```suggestion
node chooses.
```

2021-11-15 02:25 UTC, Loquacity commented on timescaledb/how-to-guides/hypertables/distributed-hypertables.md
> +insert batch size, the `INSERT` would require around three full
```suggestion
insert batch size, the `INSERT` requires around three full
```

2021-11-15 02:25 UTC, Loquacity commented on timescaledb/how-to-guides/hypertables/distributed-hypertables.md
> +Triggers on distributed hypertables work similar to triggers on
```suggestion
Triggers on distributed hypertables work in a similar way to triggers on
```

2021-11-15 02:25 UTC, Loquacity commented on timescaledb/how-to-guides/hypertables/distributed-hypertables.md
> +  trigger)
```suggestion
  nodes that a trigger fires on. This is because each replica node fires the
  trigger.
```

2021-11-15 02:25 UTC, Loquacity commented on timescaledb/how-to-guides/hypertables/distributed-hypertables.md
> +```sql
```suggestion
[`distributed_exec`][dist_exec] procedure:
```sql
```

2021-11-15 02:25 UTC, Loquacity commented on timescaledb/how-to-guides/hypertables/distributed-hypertables.md
> +```
It would be better if you could split these up, and keep the comments out of the text box.

2021-11-15 02:25 UTC, Loquacity commented on timescaledb/how-to-guides/hypertables/distributed-hypertables.md
> +Row-level triggers execute on the data node where the data is
```suggestion
Row-level triggers are executed on the data node where the data is
```

2021-11-15 02:25 UTC, Loquacity commented on timescaledb/how-to-guides/hypertables/distributed-hypertables.md
> +stored since `BEFORE` and `AFTER` row triggers need access to the
```suggestion
stored, because `BEFORE` and `AFTER` row triggers need access to the
```

2021-11-15 02:25 UTC, Loquacity commented on timescaledb/how-to-guides/hypertables/distributed-hypertables.md
> +stored data. The chunks on the access node do not actually
```suggestion
stored data. The chunks on the access node do not
```

2021-11-15 02:25 UTC, Loquacity commented on timescaledb/how-to-guides/hypertables/distributed-hypertables.md
> +Statement-level triggers will execute once on each node affected by
```suggestion
Statement-level triggers execute once on each node affected by
```

2021-11-15 02:25 UTC, Loquacity commented on timescaledb/how-to-guides/hypertables/distributed-hypertables.md
> +To avoid processing the trigger multiple times, it is recommended that
```suggestion
To avoid processing the trigger multiple times, we recommend that
```

2021-11-15 02:25 UTC, Loquacity commented on timescaledb/how-to-guides/hypertables/distributed-hypertables.md
> +the trigger function checks which node it is executing on to make sure
```suggestion
you set the trigger function to check which node it is executing on, to ensure
```

2021-11-15 02:25 UTC, Loquacity commented on timescaledb/how-to-guides/hypertables/distributed-hypertables.md
> +that the trigger action only affects the desired node. For instance,
```suggestion
that the trigger action only affects the desired node. For example,
```

2021-11-15 02:25 UTC, Loquacity commented on timescaledb/how-to-guides/hypertables/distributed-hypertables.md
> +node compared to a data node, one can define a statement-level trigger
```suggestion
node compared to a data node, you can define a statement-level trigger
```

2021-11-15 02:25 UTC, Loquacity commented on timescaledb/how-to-guides/hypertables/distributed-hypertables.md
> +
```suggestion
function like this:
```

2021-11-16 01:13 UTC, Loquacity approved these changes

2021-11-29 16:10 UTC, merged