Clarify what functionality of time_bucket_ng() is supported by CAGGs
timescale/docs pull request #627
Opened 2021-11-30 13:02 UTC by afiskon

# Description

Several users expected that since time_bucket_ng() supports months and timezones, this functionality is also supported in CAGGs. It's not clear from the documentation that it's not true. The proposed patch clarifies what is currently supported from the CAGGs side.

# Version

Which documentation version does this PR apply to?

- [ ] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

https://github.com/timescale/timescaledb/issues/414#issuecomment-954480123
Also, Slack.

2021-11-30 14:27 UTC, NunoFilipeSantos requested changes
I think this is more direct but probably @Loquacity has even a better alternative.

2021-11-30 14:27 UTC, NunoFilipeSantos commented on api/time_bucket_ng.md
> +`time_bucket_ng()` is currently supported on the continuous aggregates side:
```suggestion
Note that although `time_bucket_ng()` supports months and timezones, currently
continuous aggregates do not support months and timezones when using `time_bucket_ng()`.

The following table shows what functionality of
`time_bucket_ng()` is currently supported on the continuous aggregates side:
```

2021-12-01 03:33 UTC, Loquacity commented on api/time_bucket_ng.md
> +`time_bucket_ng()` is currently supported on the continuous aggregates side:
```suggestion
While `time_bucket_ng()` supports months and timezones, continuous aggregates cannot always be used with monthly buckets or buckets with timezones. 

This table shows which `time_bucket_ng()` functions can be used in a continuous aggregate:
```

2021-12-01 03:36 UTC, Loquacity commented on api/time_bucket_ng.md
> +Timezones support | NO
```suggestion
|Function|Available in continuous aggregate|TimescaleDB version|
|-|-|-|
|Buckets by seconds, minutes, hours, days and weeks|✅|2.4.0 and later|
|Buckets by months and years|❌|Expected in 2.6.0 or later|
|Specify custom origin|❌|To be determined|
|Timezones support|❌|To be determined|
```

2021-12-01 03:37 UTC, Loquacity commented
> I think this is more direct but probably @Loquacity has even a better alternative.

How did you guess? 😉

2021-12-01 11:41 UTC, NunoFilipeSantos approved these changes

2021-12-01 13:16 UTC, merged