Remove old default interval references
timescale/docs pull request #640
Opened 2021-12-04 01:34 UTC by solugebefola

# Description

There are references to the old default time interval (from `v0.11.0`) which don't apply anymore

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes #[insert issue link, if any]

2021-12-05 22:53 UTC, Loquacity requested changes

2021-12-05 22:53 UTC, Loquacity commented on timescaledb/how-to-guides/hypertables/best-practices.md
> +for new chunks can be changed by calling [`set_chunk_time_interval`][set_chunk_time_interval].
```suggestion
The default time interval is seven days. You can explicitly configure time 
intervals when you create a hypertable, using the `chunk_time_interval`
setting. After the hypertable is created, you can change the interval for
new chunks with [`set_chunk_time_interval`][set_chunk_time_interval].
```

2021-12-07 00:37 UTC, Loquacity approved these changes

2021-12-07 19:24 UTC, solugebefola commented
Should I merge, or do you handle all merging?

2021-12-07 23:08 UTC, merged