Add alert in promscale
timescale/docs pull request #680
Opened 2021-12-23 10:30 UTC by ramonguiu

# Description

Continue moving docs from Promscale repo to docs.timescale.com

This PR covers alerting.

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

2022-01-04 23:43 UTC, Loquacity commented
Needs editing

2022-01-31 07:14 UTC, Loquacity commented
@ramonguiu @VineethReddy02 Ready for your review.

2022-01-31 16:36 UTC, charislam approved these changes

2022-02-01 10:17 UTC, ramonguiu reviewed
Looks good. Added a small comment.

2022-02-01 10:17 UTC, ramonguiu commented on promscale/alert.md
> +Set up alerting by adding creating a YAML file containing configuration like
"adding creating" -> "creating" ?

2022-02-02 01:41 UTC, Loquacity requested changes

2022-02-02 01:41 UTC, Loquacity commented on promscale/alert.md
> +Set up alerting by adding creating a YAML file containing configuration like
```suggestion
Set up alerting by creating a YAML file containing configuration like
```

2022-02-04 12:41 UTC, ramonguiu commented
@Loquacity are there any additional reviews or changes required? It seems this one is ready to go.

2022-02-04 20:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/timescale/docs?pullRequest=680) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/timescale/docs?pullRequest=680) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: ramonguiu<br/>:white_check_mark: Loquacity<br/>:x: jacobprall<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/timescale/docs?pullRequest=680) it.</sub>

2022-02-05 20:20 UTC, VineethReddy02 approved these changes

2022-02-07 03:23 UTC, Loquacity approved these changes

2022-02-07 03:24 UTC, merged