Use a fully qualified hypertable name in an example
timescale/docs pull request #732
Opened 2022-01-21 15:14 UTC by akuzm

# Description

In an example, use the fully qualified name of the materialization hypertable, because it doesn't work otherwise.

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)

# Links

Fixes #4002

2022-01-21 15:17 UTC, fabriziomello approved these changes

2022-01-24 01:16 UTC, Loquacity requested changes

2022-01-24 01:16 UTC, Loquacity commented on timescaledb/how-to-guides/continuous-aggregates/materialized-hypertables.md
> +name of it. To do this, use the
```suggestion
To change a materialized hypertable, you need to use its fully qualified
name. To find the correct name, use the
```

2022-01-24 09:57 UTC, Loquacity approved these changes

2022-01-24 09:57 UTC, merged