Copy edit FAQs
timescale/docs pull request #767
Opened 2022-02-02 21:14 UTC by charislam

# Description

[Short summary of why you created this PR]

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes #[insert issue link, if any]

2022-02-02 21:15 UTC, charislam commented on timescaledb/overview/faq/faq-postgres.md
> +PostgreSQL once tables reach moderate size (for example, 10s of millions of rows).
```suggestion
PostgreSQL once tables reach moderate size (for example, 10&nbsp;s of millions of rows).
```

2022-02-02 21:18 UTC, charislam commented on timescaledb/overview/faq/faq-postgres.md
> +PostgreSQL once tables reach moderate size (for example, 10s of millions of rows).
```suggestion
<!-- vale Google.Units = NO -->
PostgreSQL once tables reach moderate size (for example, 10s of millions of rows).
<!-- vale Google.Units = YES -->
```

2022-02-03 00:50 UTC, Loquacity requested changes

2022-02-03 00:50 UTC, Loquacity commented on timescaledb/overview/faq/faq-postgres.md
> +partitioning is abstracted away behind a "hypertable," which users interact with just as
```suggestion
partitioning is abstracted away behind a hypertable, which users interact with just as
```

2022-02-03 00:50 UTC, Loquacity commented on timescaledb/overview/faq/faq-postgres.md
> +* Much higher ingest scale: TimescaleDB sees throughput more than 20X that of
```suggestion
* Much higher ingest scale: TimescaleDB sees throughput more than 20 times that of 
```

2022-02-03 00:50 UTC, Loquacity commented on timescaledb/overview/faq/faq-postgres.md
> +PostgreSQL once tables reach moderate size (for example, 10s of millions of
```suggestion
PostgreSQL once tables reach moderate size (for example, tens of millions of
```

2022-02-03 00:50 UTC, Loquacity commented on timescaledb/overview/faq/faq-products.md
> +anything that speaks SQL (in other words, the entire PostgreSQL ecosystem).
```suggestion
anything that speaks SQL, including the entire PostgreSQL ecosystem.
```

2022-02-03 00:50 UTC, Loquacity commented on timescaledb/overview/faq/faq-products.md
>  * If you want greater optionality when it comes to using third-party tools. TimescaleDB supports
```suggestion
* If you want more options when it comes to using third-party tools. TimescaleDB supports
```

2022-02-03 00:50 UTC, Loquacity commented on timescaledb/overview/faq/faq-products.md
> +* If you already use and like PostgreSQL, and don't want to "give it up" and move to a
```suggestion
* If you already use and like PostgreSQL, and don't want to give it up and move to a
```

2022-02-03 00:50 UTC, Loquacity commented on timescaledb/overview/faq/faq-products.md
>  like TimescaleDB and PostgreSQL are better suited).
```suggestion
perform well for more complex queries, where relational databases
like TimescaleDB and PostgreSQL are better suited.
```

2022-02-03 00:50 UTC, Loquacity commented on timescaledb/overview/faq/faq-using-timescaledb.md
> +two-dimensional "chunks" (smaller PostgreSQL tables), performing
```suggestion
two-dimensional chunks that operate like smaller PostgreSQL tables, performing
```

2022-02-04 01:27 UTC, Loquacity approved these changes

2022-02-04 17:06 UTC, merged

2022-02-07 03:01 UTC, Loquacity commented
Don't forget to update the PR description 😉