Structural and line edit on concepts/hypertables
timescale/docs pull request #810
Opened 2022-02-12 00:07 UTC by charislam

# Description

Make conceptual information on hypertables and chunks more scannable and beginner-friendly with structural and line edits

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Partial #801

2022-03-03 01:05 UTC, charislam commented
Draft of index and chunks diagram (need SME input)
![indexes-chunks drawio](https://user-images.githubusercontent.com/26616127/156476304-268e762f-9237-4d58-a3ff-fb8a1ff29314.svg)

2022-03-04 00:26 UTC, charislam commented
@ryanbooz I am rewriting the concept guides to be more scannable and beginner-friendly. Could you take a look? I also have a rough sketch of a diagram to explain local indexes, which I'm sure could do with a lot of improvements. Thanks!

2022-03-07 03:03 UTC, Loquacity requested changes

2022-03-07 03:03 UTC, Loquacity commented on timescaledb/overview/core-concepts/hypertables-and-chunks.md
> +belongs in by looking at its time value *and* its device ID.
```suggestion
belongs in by looking at its time value and its device ID. 
```

2022-03-07 03:03 UTC, Loquacity commented on timescaledb/overview/core-concepts/hypertables-and-chunks.md
```suggestion
```

2022-03-07 03:03 UTC, Loquacity commented on timescaledb/overview/core-concepts/hypertables-and-chunks.md
> +In PostgreSQL vocabulary, the hypertable is a "parent table" and the chunks are
terminology?

2022-03-07 03:03 UTC, Loquacity commented on timescaledb/overview/core-concepts/hypertables-and-chunks.md
> +To enforce each chunk's time boundaries, each chunk includes constraints. For
includes *time* constraints?

2022-03-07 03:03 UTC, Loquacity commented on timescaledb/overview/core-concepts/hypertables-and-chunks.md
> +All of this happens in the background, transparently to the user.
Third person.

2022-03-07 03:03 UTC, Loquacity commented on timescaledb/overview/core-concepts/hypertables-and-chunks.md
> +week. It excludes any chunks from before that time.
This section feels like it needs fewer para breaks.

2022-03-07 03:03 UTC, Loquacity commented on timescaledb/overview/core-concepts/hypertables-and-chunks.md
> +
```suggestion
```

2022-03-07 03:03 UTC, Loquacity commented on timescaledb/overview/core-concepts/hypertables-and-chunks.md
> +two methods can be used:
```suggestion
choose from one of these two methods:
```

2022-03-07 17:25 UTC, charislam commented on timescaledb/overview/core-concepts/hypertables-and-chunks.md
> +In PostgreSQL vocabulary, the hypertable is a "parent table" and the chunks are
```suggestion
In PostgreSQL terminology, the hypertable is a "parent table" and the chunks are
```
```suggestion
In PostgreSQL vocabulary, the hypertable is a "parent table" and the chunks are
```

2022-03-07 17:25 UTC, charislam commented on timescaledb/overview/core-concepts/hypertables-and-chunks.md
> +In PostgreSQL vocabulary, the hypertable is a "parent table" and the chunks are
```suggestion
In PostgreSQL terminology, the hypertable is a "parent table" and the chunks are
```
```suggestion
In PostgreSQL vocabulary, the hypertable is a "parent table" and the chunks are
```

2022-03-07 17:26 UTC, charislam commented on timescaledb/overview/core-concepts/hypertables-and-chunks.md
> +To enforce each chunk's time boundaries, each chunk includes constraints. For
```suggestion
To enforce each chunk's time boundaries, each chunk includes time constraints. For
```
```suggestion
To enforce each chunk's time boundaries, each chunk includes constraints. For
```

2022-03-08 19:46 UTC, davidkohn88 reviewed
Looking good generally, I left a few comments. I think the section on indexes is a little hard to grok and could be a good place for a few diagrams.

2022-03-15 19:42 UTC, charislam commented on timescaledb/overview/core-concepts/hypertables-and-chunks-benefits.md
> +chunk implies global uniqueness.
I took a stab at making diagrams for this, would love some feedback here! https://iobeam.slack.com/archives/C0360448V6X/p1647371342405649

2022-03-21 01:04 UTC, Loquacity commented on timescaledb/overview/core-concepts/hypertables-and-chunks/chunk-architecture.md
> +Like time partitions, space partitions are always non-overlapping.
```suggestion
Like time partitions, space partitions never overlap.
```

2022-03-21 01:04 UTC, Loquacity commented on timescaledb/overview/core-concepts/hypertables-and-chunks/hypertables-and-chunks-benefits.md
> +To learn about chunk sizing for improved performance, see the section on
```suggestion
For more information about chunk sizing for improved performance, see the section on 
```

2022-03-21 14:39 UTC, charislam commented on timescaledb/overview/core-concepts/hypertables-and-chunks/index.md
> +time intervals, see the documentation on [chunk sizing](FIXME).
```suggestion
time intervals, see the documentation on [chunk sizing](timescaledb/latest/how-to-guides/hypertables/best-practices/#time-intervals).
```

2022-03-22 00:00 UTC, Loquacity requested changes
Just noticed a bunch of links broken across lines.

2022-03-22 00:00 UTC, Loquacity commented on timescaledb/overview/core-concepts/hypertables-and-chunks/chunk-architecture.md
> +local indexes][hypertable-benefits-indexes].
```suggestion
speed for recent data. For more information, see the section on the 
[benefits of local indexes][hypertable-benefits-indexes].
```

2022-03-23 01:15 UTC, Loquacity approved these changes

2022-04-22 01:19 UTC, Loquacity commented on timescaledb/overview/core-concepts/hypertables-and-chunks/index.md
> +performance and user experience for time series.
```suggestion
performance and user experience for time series data.
```

2022-04-26 04:44 UTC, Loquacity commented on timescaledb/overview/core-concepts/hypertables-and-chunks/hypertable-architecture.md
> +partitioning."
```suggestion
also be partitioned by other columns. This is called time-and-space
partitioning.
```

2022-04-26 04:44 UTC, Loquacity commented on timescaledb/overview/core-concepts/hypertables-and-chunks/hypertables-and-chunks-benefits.md
> +according to the newer setup. Thus, data retention eventually rebalances data
"Thus"?

2022-04-26 04:44 UTC, Loquacity commented on timescaledb/overview/core-concepts/hypertables-and-chunks/index.md
> +You can! You can plan and write all the partitioning logic yourself on regular
Not sure I like this construction 😕

2022-04-26 19:44 UTC, charislam commented on timescaledb/overview/core-concepts/hypertables-and-chunks/index.md
> +writing the partitioning logic yourself. But handling child tables, constraints,
@Loquacity is this better?

2022-04-27 00:24 UTC, Loquacity approved these changes

2022-08-08 05:09 UTC, Loquacity commented
@charislam I think that this can be merged, when you're ready.

2022-08-17 18:55 UTC, davidkohn88 commented
Did you want another look from me on this? I think we're ready to merge? I just keep getting pinged about it...

2022-08-17 18:59 UTC, charislam commented
Sorry @davidkohn88, I think we can just go ahead and merge, I'll do that now to stop the constant notifs :)

2022-08-17 19:19 UTC, charislam commented on timescaledb/overview/core-concepts/hypertables-and-chunks/hypertable-architecture.md
> +[hypertable-benefits-indexes]: /overview/core-concepts/hypertables-and-chunks/hypertables-and-chunks-benefits/#faster-index-updates
```suggestion
[distributed-hypertables]: /timescaledb/:currentVersion:/overview/core-concepts/distributed-hypertables/
[hypertable-benefits-indexes]: /timescaledb/:currentVersion:/overview/core-concepts/hypertables-and-chunks/hypertables-and-chunks-benefits/#faster-index-updates
```

2022-08-17 19:19 UTC, charislam commented on timescaledb/overview/core-concepts/hypertables-and-chunks/hypertables-and-chunks-benefits.md
> +[local-indexes]: /overview/core-concepts/hypertables-and-chunks/chunk-architecture/#chunk-local-indexes
```suggestion
[data-retention]: /timescaledb/:currentVersion:/how-to-guides/data-retention/
[local-indexes]: /timescaledb/:currentVersion:/overview/core-concepts/hypertables-and-chunks/chunk-architecture/#chunk-local-indexes
```

2022-08-17 19:19 UTC, charislam commented on timescaledb/overview/core-concepts/hypertables-and-chunks/hypertables-and-chunks-benefits.md
> +[replication]: /how-to-guides/replication-and-ha/
```suggestion
[replication]: /timescaledb/:currentVersion:/how-to-guides/replication-and-ha/
```

2022-08-17 19:19 UTC, charislam commented on timescaledb/overview/core-concepts/hypertables-and-chunks/index.md
> +[hypertable-how-to]: /how-to-guides/hypertables/
```suggestion
[hypertable-architecture]: /timescaledb/:currentVersion:/overview/core-concepts/hypertables-and-chunks/hypertable-architecture/
[hypertable-benefits]: /timescaledb/:currentVersion:/overview/core-concepts/hypertables-and-chunks/hypertables-and-chunks-benefits/
[hypertable-how-to]: /how-to-guides/hypertables/
```

2022-08-17 19:20 UTC, merged