Update  pg_restore limitations
timescale/docs pull request #820
Opened 2022-02-16 18:20 UTC by gayyappan

# Description
pg_restore with -j option does not work for timescaledb extension

# Version
All

Which documentation version does this PR apply to?

- [x ] Latest (Default)
any older version of the docs that we still maintain.
This is an old problem that has not been documented.

# Links

Fixes https://github.com/timescale/timescaledb/issues/4101

2022-02-17 01:15 UTC, Loquacity requested changes

2022-02-17 01:15 UTC, Loquacity commented on timescaledb/how-to-guides/backup-and-restore/pg-dump-and-restore.md
> +while restoring the timescale catalogs.
```suggestion
Do not use the `pg_restore` command with the `-j` option. This option does not 
correctly restore the Timescale catalogs.
```

2022-02-18 02:15 UTC, Loquacity approved these changes

2022-02-18 14:12 UTC, merged

2023-06-26 14:59 UTC, JamesGuthrie commented
This issue in the timescaledb repo tracks the underlying problem: https://github.com/timescale/timescaledb/issues/698