Add instructions for installing Toolkit from package
timescale/docs pull request #838
Opened 2022-02-18 17:56 UTC by charislam

# Description

TimescaleDB toolkit is now available as an Ubuntu, Debian, or RPM package. This PR adds package installation instructions to the Toolkit install guide.

Also includes:
- Minor fixes to align with branding and style guide
- Spell out reference links so Vale can check for broken links

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes #541

2022-02-18 17:58 UTC, charislam commented
@svenklemm I started revising the Toolkit installation page to mention the Debian/Ubuntu/RPM packages. Disclaimer: I hacked together the procedures from minimal understanding of Linux so they may be utterly wild. Corrections much appreciated!

2022-02-19 19:59 UTC, svenklemm commented
Looks good, maybe put in link how to install timescaledb repo for folks that don't have it yet

2022-02-20 23:05 UTC, Loquacity requested changes

2022-02-20 23:05 UTC, Loquacity commented on timescaledb/how-to-guides/hyperfunctions/install-toolkit.md
> +These instructions use the `dnf` package manager on RHEL, CentOS, and Fedora.
Move this line out of the procedure.

2022-02-20 23:05 UTC, Loquacity commented on timescaledb/how-to-guides/hyperfunctions/install-toolkit.md
> +    repository in your `yum` repos. For more information, see [the installation
```suggestion
    repository in your `yum` repo.d directory. For more information, see [the installation
```

??

2022-02-20 23:05 UTC, Loquacity commented on timescaledb/how-to-guides/hyperfunctions/install-toolkit.md
> +These instructions use the `apt` package manager on Debian and Ubuntu.
Move out of the procedure.

2022-02-22 18:51 UTC, charislam commented on timescaledb/how-to-guides/hyperfunctions/install-toolkit.md
> +    repository in your `yum` repos. For more information, see [the installation
```suggestion
    repository in your `yum` `repo.d` directory. For more information, see [the installation
```

2022-02-22 19:19 UTC, charislam commented
> Looks good, maybe put in link how to install timescaledb repo for folks that don't have it yet

Thanks @svenklemm! The repo install instructions are at the same link as the install TimescaleDB instructions; I reworded the link text so hopefully that's a bit clearer now

2022-02-23 00:34 UTC, Loquacity approved these changes

2022-03-01 17:37 UTC, merged