[Update] Install self-hosted TimescaleDB from a pre-built cloud image
timescale/docs pull request #856
Opened 2022-02-23 06:21 UTC by Rajakavitha1

# Description

Created a new TimescaleDB instance on AWS EC2 and updated the instructions.

The commands `psql -U postgres -h localhost` are applicable only if you installed in on self hosted local host.
# Version

Which documentation version does this PR apply to?

- [ *] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes #[insert issue link, if any]
<img width="563" alt="Screenshot 2022-02-23 at 11 47 40 AM" src="https://user-images.githubusercontent.com/37059749/155270417-f0e8bd28-6da2-40f8-8cc0-06147eafe14a.png">

2022-02-23 19:46 UTC, charislam approved these changes

2022-02-23 19:46 UTC, charislam commented on install/installation-cloud-image.md
> +After you run the *timescaledb-tune* script you need to restart the PostgreSQL service for the configuration changes to take effect. To restart the service use the **sudo systemctl restart postgresql
```suggestion
After running the `timescaledb-tune` script, you need to restart the PostgreSQL service for the configuration changes to take effect. To restart the service, run `sudo systemctl restart postgresql.service`.
```

2022-02-23 19:46 UTC, charislam commented on install/installation-cloud-image.md
> +When you have PostgreSQL and TimescaleDB installed, connect to your instance and setup the TimescaleDB extension.
```suggestion
When you have PostgreSQL and TimescaleDB installed, connect to your instance and set up the TimescaleDB extension.
```

2022-02-23 19:46 UTC, charislam commented on install/installation-cloud-image.md
> +1.  At the prompt, create an empty database. Our database is
```suggestion
1.  At the prompt, create an empty database. For example, to create a database
```

2022-03-01 01:15 UTC, Loquacity requested changes

2022-03-01 01:15 UTC, Loquacity commented on install/installation-cloud-image.md
> +1.  Navigate to **Images > AMIs**.
```suggestion
1.  Navigate to `Images → AMIs`.
```

2022-03-01 01:15 UTC, Loquacity commented on install/installation-cloud-image.md
> +1.  Select the image you want to use, and click **Launch instance from image**.
```suggestion
1.  Select the image you want to use, and click `Launch instance from image`.
```

2022-03-01 01:20 UTC, Rajakavitha1 commented
Hi @Loquacity !!! Just incorporated the changes that you suggested.

2022-03-01 01:40 UTC, Loquacity approved these changes

2022-03-03 21:16 UTC, svenklemm commented
What is the difference between install/installation-cloud-image.md and install/installation-ubuntu-ami.md? Can we drop the latter?

2022-03-07 02:40 UTC, Rajakavitha1 commented
> What is the difference between install/installation-cloud-image.md and install/installation-ubuntu-ami.md? Can we drop the latter?

@Loquacity  can you please help me answer this for @svenklemm.  I did read the contents of install/installation-ubuntu-ami.md and yes, may be we can drop that.

2022-03-07 03:22 UTC, Loquacity commented
> > What is the difference between install/installation-cloud-image.md and install/installation-ubuntu-ami.md? Can we drop the latter?
> 
> @Loquacity can you please help me answer this for @svenklemm. I did read the contents of install/installation-ubuntu-ami.md and yes, may be we can drop that in a different PR. @svenklemm could you please review this PR for technical accuracy and state your approval.

install/installation-ubuntu-ami.md is not published. It can be deleted.

2022-03-07 04:31 UTC, Rajakavitha1 commented
> > > What is the difference between install/installation-cloud-image.md and install/installation-ubuntu-ami.md? Can we drop the latter?
> > 
> > 
> > @Loquacity can you please help me answer this for @svenklemm. I did read the contents of install/installation-ubuntu-ami.md and yes, may be we can drop that in a different PR. @svenklemm could you please review this PR for technical accuracy and state your approval.
> 
> install/installation-ubuntu-ami.md is not published. It can be deleted.

Deleted the file install/installation-ubuntu-ami.md based on the review feedback

2022-03-07 12:43 UTC, svenklemm approved these changes
LGTM, i like that we no longer have to update the image ids going forward.

2022-03-08 00:52 UTC, Loquacity approved these changes
Approved, but please fix the line breaks before merge.

2022-03-08 00:52 UTC, Loquacity commented on install/installation-cloud-image.md
> +After you have completed the installation, connect to your instance and configure your database. For information about connecting to the instance, see the AWS [accessing instance documentation][aws-c
Break at 80 chars

2022-03-08 02:34 UTC, Rajakavitha1 commented on install/installation-cloud-image.md
> +After you have completed the installation, connect to your instance and configure your database. For information about connecting to the instance, see the AWS [accessing instance documentation][aws-c
added line breaks

2022-03-08 02:35 UTC, merged