Restructure and update contributing guides
timescale/docs pull request #871
Opened 2022-02-25 19:11 UTC by charislam

# Description

Contributing and style information is spread between multiple places: two contributing pages on the docs site, `README.md`, and `CONTRIBUTING.md`. This PR reorganizes the information to make it more discoverable and less overlapping, so others find it easier to contribute to our docs.

## Changes so far

### `CONTRIBUTING.md`
- Restructure to include Github workflow information, repository structure, and markup conventions. Making this information available in one place makes it less overwhelming to get started
- Rewrite GitHub workflow instructions to generally follow docs conventions on procedures
- Remove `<highlight>`s as they don't display in GitHub, and the file isn't viewable from the docs site

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes #[insert issue link, if any]

2022-03-01 17:32 UTC, charislam commented
@Loquacity @jacobprall I'd like to move the Contributing pages into their own top-level section unless you feel there's a good reason not to. I think they will be more discoverable at the top level.

I changed the `page-index.js` files to move them, and I checked that the URLs work as expected. But they don't appear in the nav. How do I add a new top-level section to nav?

2022-03-02 01:21 UTC, Loquacity requested changes

2022-03-02 01:21 UTC, Loquacity commented on contribute-to-timescaledb/contribute-to-docs.md
> +Join the community in making Timescale documentation even better. You can
```suggestion
Join the community to help make Timescale documentation even better. You can
```

2022-03-02 01:21 UTC, Loquacity commented on contribute-to-timescaledb/contribute-to-docs.md
> +are highly welcome.
```suggestion
are always welcome.
```

2022-03-02 01:21 UTC, Loquacity commented on contribute-to-timescaledb/contribute-to-docs.md
> +
```suggestion
```

2022-03-02 01:21 UTC, Loquacity commented on contribute-to-timescaledb/contribute-to-docs.md
> +    *   Information when it's needed, where it's needed
```suggestion
    *   Information where it's needed, when it's needed
```

2022-03-02 01:21 UTC, Loquacity commented on contribute-to-timescaledb/contribute-to-docs.md
> +better. For example, the most important words come first in an English sentence.
```suggestion
the purpose better. For example, the most important words come first in an English sentence.
```

2022-03-02 01:21 UTC, Loquacity commented on contribute-to-timescaledb/contribute-to-docs.md
> +first, even if it means using passive.
```suggestion
first, even if it means using passive voice.
```

2022-03-02 01:21 UTC, Loquacity commented on contribute-to-timescaledb/contribute-to-docs.md
> +
I have a way of explaining this where I point out that, in technical documentation, we almost always know who the actor is (it's the reader, "you"), so in most cases the action is actually the most important part of the sentence ("Install the thing", "Configure the thing", etc). Feel free to construct that into a more useful piece of advice here, if you think it's useful 😉

2022-03-02 01:21 UTC, Loquacity commented on contribute-to-timescaledb/contribute-to-docs.md
> +If the object of an action is the most important part of a sentence, put it
```suggestion
If the object or the action is the most important part of a sentence, put it
```

2022-03-02 01:21 UTC, Loquacity commented on contribute-to-timescaledb/contribute-to-docs.md
> +### Information when it's needed, where it's needed
```suggestion
### Information where it's needed, when it's needed
```

2022-03-02 01:21 UTC, Loquacity commented on contribute-to-timescaledb/contribute-to-docs.md
> +
Perhaps add a reference to Every Page is Page One here? Or is that going too much into the content strategy weeds?

2022-03-02 01:21 UTC, Loquacity commented on contribute-to-timescaledb/contribute-to-docs.md
> +: Do not use. Use second person ("you") instead.
I think we can safely say to use this judiciously, and only when we're referring to Timescale (the company). As in, "We strongly recommend you upgraded to the newest version of TimescaleDB", etc. I think it's better to try adn avoid it, generally, but there are definitely places where I would prefer to use "we" over "Timescale" to suit our company voice better.

2022-03-02 01:21 UTC, Loquacity commented on contribute-to-timescaledb/index.md
> +Join the community in making TimescaleDB even better. You can contribute to the
```suggestion
Join the community ito make TimescaleDB even better. You can contribute to the
```

2022-03-02 01:21 UTC, Loquacity commented on contribute-to-timescaledb/index.md
> +both of which available on GitHub. Issues and pull requests are highly welcome.
```suggestion
both of which are available on GitHub. Issues and pull requests are always welcome.
```

2022-03-02 16:07 UTC, charislam commented on CONTRIBUTING.md
> +requests are highly welcome.
```suggestion
requests are always welcome. 
```

2022-03-11 02:20 UTC, Loquacity approved these changes

2022-03-11 02:20 UTC, Loquacity commented on timescaledb/page-index/page-index.js
> +        excerpt:"Learn more about how to contribute to TimescaleDB",
```suggestion
        excerpt:"Learn how to contribute to TimescaleDB",
```

2022-03-11 02:20 UTC, Loquacity commented on timescaledb/page-index/page-index.js
> +        tags: ["timescaledb", "overview", "get started", "learn"],
```suggestion
        tags: ["contribute", "get started", "timescaledb"],
```

2022-03-11 02:20 UTC, Loquacity commented on timescaledb/page-index/page-index.js
> +        tags:["timescaledb", "get started", "learn", "contribute"],
```suggestion
        tags:["contribute", "documentation", "get started"],
```

2022-03-11 02:20 UTC, Loquacity commented on timescaledb/page-index/page-index.js
> +        excerpt:"Learn more about how to contribute to TimescaleDB documentation",
```suggestion
        excerpt:"Learn how to contribute to Timescale documentation",
```

2022-03-21 00:56 UTC, Loquacity commented
This doesn't seem to be working in preview.

2022-04-14 02:05 UTC, Loquacity commented on CONTRIBUTING.md
> +|`relatedPages`|Optional|An array of pathnames to be displayed as Related Content at the bottom of the page. For example, `["/promscale/:currentVersion:/installation/"]`|
```suggestion
|`relatedPages`|Optional|An array of path names to be displayed as Related Content at the bottom of the page. For example, `["/promscale/:currentVersion:/installation/"]`|
```

2022-08-04 02:04 UTC, charislam commented
We will not be moving contributing to top level in near future. Going to take this PR apart into several parts to make some other improvements to our contributing docs.

2022-08-04 02:04 UTC, closed without merging