[Update] Manual Compression
timescale/docs pull request #906
Opened 2022-03-07 12:13 UTC by Rajakavitha1

# Description

It uses this command:
SELECT compress_chunk(i) from show_chunks('example', now() - interval '1 week', now() - interval '3 weeks') i;
I think it would be better to suggest using the if_not_compressed argument in order to not error out if there are already compressed chunks in the interval, i.e.
SELECT compress_chunk(i, if_not_compressed => true) from show_chunks('example', now() - interval '1 week', now() - interval '3 weeks') i;

# Version

Which documentation version does this PR apply to?

- [*] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes #[insert issue link, if any]
[903
](https://github.com/timescale/docs/issues/903)

2022-03-08 04:38 UTC, Loquacity approved these changes

2022-03-08 04:45 UTC, Rajakavitha1 commented on timescaledb/how-to-guides/compression/manually-compress-chunks.md
> +SELECT compress_chunk(i, if_not_compressed => true) from show_chunks('example', now() - interval '1 week', now() - interval '3 weeks') i;
Just added an explanation.

2022-03-08 05:14 UTC, Loquacity requested changes

2022-03-08 05:14 UTC, Loquacity commented on timescaledb/how-to-guides/compression/manually-compress-chunks.md
```suggestion
```

2022-03-08 15:22 UTC, charislam approved these changes

2022-03-09 04:36 UTC, Loquacity requested changes

2022-03-09 04:36 UTC, Loquacity commented on timescaledb/how-to-guides/compression/manually-compress-chunks.md
> +example, use the following command to compress chunks between one and three weeks old
```suggestion
example, use this command to compress chunks between one and three weeks old 
```

2022-03-09 06:05 UTC, Loquacity approved these changes

2022-03-09 06:18 UTC, merged