Add API reference for `recompress_chunk`
timescale/docs pull request #966
Opened 2022-03-22 00:01 UTC by charislam

# Description

Add API reference for `recompress_chunk` procedure. Include troubleshooting information about changes in TimescaleDB 2.6.0.

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes #892

2022-03-22 02:21 UTC, Loquacity requested changes

2022-03-22 02:21 UTC, Loquacity commented on api/recompress_chunk.md
> +control by allowing you to target a specific chunk.
```suggestion
You can also recompress chunks by 
[running the job associated with your compression policy][run-job]. 
`recompress_chunk` gives you more fine-grained control by 
allowing you to target a specific chunk.
```

2022-03-22 02:21 UTC, Loquacity commented on api/recompress_chunk.md
> +`recompress_chunk` is implemented as a SQL procedure and not a function. Call
```suggestion
`recompress_chunk` is implemented as an SQL procedure and not a function. Call
```

2022-03-22 02:21 UTC, Loquacity commented on api/recompress_chunk.md
> +the procedure with `CALL` rather than using a `SELECT` statement.
```suggestion
the procedure with `CALL`, do not use a `SELECT` statement.
```

2022-03-22 02:21 UTC, Loquacity commented on api/recompress_chunk.md
> +`recompress_chunk` only works on previously compressed chunks. To compress a
```suggestion
`recompress_chunk` only works on chunks that have previously been compressed. To compress a
```

2022-03-22 02:21 UTC, Loquacity commented on api/recompress_chunk.md
> +Since TimescaleDB 2.6.0, `recompress_chunk` is implemented as a procedure.
```suggestion
In TimescaleDB 2.6.0 and above, `recompress_chunk` is implemented as a procedure.
```

2022-03-22 02:21 UTC, Loquacity commented on api/recompress_chunk.md
> +TimescaleDB 2.6.0 or later, older code that uses `recompress_chunk` as a
```suggestion
TimescaleDB 2.6.0 or above, the`recompress_chunk` 
```

2022-03-22 02:21 UTC, Loquacity commented on api/recompress_chunk.md
> +function may cause an error. For example, trying to run `SELECT
```suggestion
function could cause an error. For example, trying to run `SELECT
```

2022-03-22 02:21 UTC, Loquacity commented on api/recompress_chunk.md
> +To fix the error, use `CALL` instead of `SELECT`. You may need to write a
```suggestion
To fix the error, use `CALL` instead of `SELECT`. You might also need to write a
```

2022-03-22 14:29 UTC, charislam commented on api/recompress_chunk.md
> +the procedure with `CALL` rather than using a `SELECT` statement.
```suggestion
the procedure with `CALL`. Don't use a `SELECT` statement.
```

2022-03-23 01:07 UTC, Loquacity approved these changes

2022-04-17 11:02 UTC, svenklemm commented on api/recompress_chunk.md
> +Recompresses a chunk that was previously compressed and decompressed.
```suggestion
Recompresses a chunk that is compressed and had INSERTs after compression.
```

2022-04-17 11:05 UTC, svenklemm commented on api/recompress_chunk.md
> +|`chunk`|`REGCLASS`|The chunk to be recompressed. Must preface with the schema, `_timescaledb_internal`.|
```suggestion
|`chunk`|`REGCLASS`|The chunk to be recompressed. Must include the schema if not in `search_path`, e.g. `_timescaledb_internal`.|
```

2022-04-20 13:57 UTC, svenklemm approved these changes

2022-04-20 16:03 UTC, merged