Update OpenTelemetry send data to Promscale
timescale/docs pull request #976
Opened 2022-03-23 10:58 UTC by VineethReddy02

# Description

Add OpenTelemetry send data details. 

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)

# Links

Fixes #925

2022-03-24 00:38 UTC, Loquacity commented on promscale/send-data/opentelemetry.md
> +With below configuration you can send the traces from Jaeger and OpenTelemetry applications to the collector and can be exported the ame to Promscale.
```suggestion
With this configuration you can send the traces from Jaeger and OpenTelemetry applications to the collector and export them to Promscale. 
```

2022-03-24 00:38 UTC, Loquacity commented on promscale/send-data/opentelemetry.md
> +## Send the data using OpenTelemetry instrumentation
```suggestion
## Send data using OpenTelemetry instrumentation
```

2022-03-24 00:38 UTC, Loquacity commented on promscale/send-data/opentelemetry.md
> +observability backend in production as it offers batching, queued retries and many other functionalities by configuring the processors. However, you can also send data from
```suggestion
observability backend in production as it offers batching, queued retries, and other functions by configuring the processors. However, you can also send data from 
```

2022-03-24 00:38 UTC, Loquacity commented on promscale/send-data/opentelemetry.md
> +With Opentelemetry SDKs you can configure the exporter backend using `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` environment variable on your applications end.
```suggestion
With Opentelemetry SDKs you can configure the exporter backend using the `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` environment variable on your applications' end. 
```

2022-04-06 02:06 UTC, Loquacity requested changes
I didn't mention it inline, but the whole document needs reflowing for line length, too.

2022-04-06 02:06 UTC, Loquacity commented on promscale/send-data/opentelemetry.md
> +  * **Exporters**: OpenTelemetry line protocol configure the Promscale gRPC server to export the data to Promscale, queue_size to hold the data before dropping and `timeout` is timeout for write requ
```suggestion
  * **Exporters**: OpenTelemetry line protocol to configure the Promscale gRPC server to export the data to Promscale. Use `queue_size` to hold the data before dropping, and `timeout` for the write request to the backend. Prometheus remote write exports the OpenTelemetry line protocol metrics to the Prometheus remote storage backend. Configure the Promscale HTTP endpoint to ingest the metrics. 
```

Not 100% sure on this edit, please check.

2022-04-06 02:06 UTC, Loquacity commented on promscale/send-data/opentelemetry.md
> +  * **Service**: Pipeline is to configure to receive the data from Jaeger and OTLP (traces, metrics), batch process them and to export the data in logs and to OTLP, Prometheus supported backends.
```suggestion
  * **Service**: Pipeline to configure to receive the traces and metrics from Jaeger and OTLP, batch process them, and export the data in logs to OTLP and Prometheus-supported backends.
```

2022-04-06 02:06 UTC, Loquacity commented on promscale/send-data/opentelemetry.md
> +observability backend in production as it offers batching, queued retries, and many other functions by configuring the processors. However, you can also send data from
```suggestion
observability backend in production as it offers batching, queued retries, and many other functions by configuring the processors. However, you can also send data from 
```

We need to add guidance on hyphenation for words like backend to our word usage guide. For `backend` IBM says to hyphenate, Google says one word 🤷‍♀️

2022-04-12 02:17 UTC, Loquacity requested changes
Still needs reflowing for line length.

2022-04-13 09:09 UTC, Rajakavitha1 commented
Hi @VineethReddy02 !!!! installed using [helm](https://github.com/open-telemetry/opentelemetry-helm-charts). Validated the configurations.

2022-04-13 09:16 UTC, Rajakavitha1 approved these changes

2022-04-13 13:33 UTC, VineethReddy02 commented on promscale/send-data/opentelemetry.md
> +      insecure: true
Works as a starting point `insecure` should be fine, using TLS adds additional friction for the users getting started as it needs configuring certs both on the collector and Promscale end.

We can re-iterate over this based on incoming requests from the users on TLS.

2022-04-13 13:35 UTC, VineethReddy02 commented on promscale/send-data/opentelemetry.md
> +      exporters: [logging, otlp]
logging exporter logs the state that spans are being ingested. It doesn't log the content of the trace it's optional. I will drop as it as no influence on the settings.

2022-04-13 15:29 UTC, Rajakavitha1 commented on promscale/send-data/opentelemetry.md
> +metrics are converted into Prometheus remote write format in OpenTelemetry
rephrased as: You can send metrics to Promscale
**HTTP** endpoint using Prometheus remote write protocol with the OpenTelemetry
Collector. OpenTelemetry Collector converts OTLP metrics to Prometheus remote
write protocol metrics.

2022-04-19 02:18 UTC, Loquacity requested changes

2022-04-19 02:18 UTC, Loquacity commented on promscale/send-data/opentelemetry.md
> +see [Promscale CLI reference][promscale-cli].
```suggestion
see the [Promscale CLI reference][promscale-cli].
```

2022-04-19 02:18 UTC, Loquacity commented on promscale/send-data/opentelemetry.md
> +>>>>>>> 48d6b2516b0d63b476dc3049714385792ba3e723
Merge conflict markers here.

2022-04-26 10:44 UTC, VineethReddy02 commented on promscale/send-data/opentelemetry.md
> +>>>>>>> 48d6b2516b0d63b476dc3049714385792ba3e723
These merge conflict markers don't exist anymore.

2022-04-27 00:19 UTC, Loquacity approved these changes

2022-04-27 00:19 UTC, Loquacity commented on promscale/send-data/opentelemetry.md
> +more information, see [OpenTelemetry documentation][otel-docs].
```suggestion
more information, see the [OpenTelemetry documentation][otel-docs].
```

2022-04-28 10:39 UTC, merged