updates to include extra docker step
timescale/docs pull request #978
Opened 2022-03-23 20:54 UTC by mirandaauhl

# Description

Update getting started add data page to include extra docker step. Also update format of table outline, seemed a little off after seeing live?

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

2022-03-23 21:58 UTC, charislam approved these changes

2022-03-23 21:58 UTC, charislam commented on timescaledb/getting-started/add-data.md
> +The dataset contains second-by second stock-trade data for the top 100 most-traded symbols, in a
```suggestion
The dataset contains second-by-second stock-trade data for the top 100 most-traded symbols, in a 
```

2022-03-23 21:58 UTC, charislam commented on timescaledb/getting-started/add-data.md
> +1.  For folks using Docker containers, you will have to add the data files to your container before
```suggestion
1.  If you're using a Docker container, add the data files to your container before 
```

2022-03-23 22:10 UTC, charislam reviewed
Noticed a bit of broken formatting due to indents

2022-03-23 22:10 UTC, charislam commented on timescaledb/getting-started/add-data.md
>      * day_volume (int): number of shares traded each day, NULL values indicate the market is closed
```suggestion
* time (timestamptz): timestamp column incrementing second by second
* symbol (text): symbols representing a company, mapped to company names in the `company` table
* price (double precision): stock quote price for a company at the given timestamp
* day_volume (int): number of shares traded each day, NULL values indicate the market is closed
```

Assuming this isn't intended to be a code block anymore? One little annoying thing about Markdown: if they're used outside of a nested list, indents automatically create code blocks.

2022-03-23 22:10 UTC, charislam commented on timescaledb/getting-started/add-data.md
>      * name (text): corresponding company name
```suggestion
* symbol (text): the symbol representing a company name
* name (text): corresponding company name
```

2022-03-23 22:10 UTC, charislam commented on timescaledb/getting-started/add-data.md
> +information, and one with real-time stock trades for one month.
```suggestion
    information, and one with real-time stock trades for one month.
```

2022-03-24 00:42 UTC, Loquacity commented on timescaledb/getting-started/add-data.md
> +names, in a table named `company`. `company` is not a hypertable.
```suggestion
names, in an ordinary SQL table named `company`.
```

2022-03-24 00:42 UTC, Loquacity commented on timescaledb/getting-started/add-data.md
> +1.  Download the following `.zip` file. The file contains two `.csv` files: one with company
```suggestion
1.  Download this `.zip` file. The file contains two `.csv` files: one with company 
```

2022-03-24 00:44 UTC, Loquacity requested changes

2022-03-24 00:44 UTC, Loquacity commented on timescaledb/getting-started/add-data.md
> +your current directory, replace the file paths as needed:
The numbering is resetting here:

![image](https://user-images.githubusercontent.com/3914967/159819655-d5e84356-3441-47ed-8e3f-01a369f6d022.png)

2022-03-24 16:36 UTC, mirandaauhl commented on timescaledb/getting-started/add-data.md
> +names, in a table named `company`. `company` is not a hypertable.
```suggestion
names, in an ordinary PostgreSQL table named `company`. 
```

2022-03-24 16:52 UTC, mirandaauhl commented on timescaledb/getting-started/add-data.md
> +* day_volume (int): number of shares traded each day, NULL values indicate the market is closed
```suggestion
- time (timestamptz): timestamp column incrementing second by second
- symbol (text): symbols representing a company, mapped to company names in the `company` table
- price (double precision): stock quote price for a company at the given timestamp
- day_volume (int): number of shares traded each day, NULL values indicate the market is closed
```

2022-03-24 16:52 UTC, mirandaauhl commented on timescaledb/getting-started/add-data.md
> +* name (text): corresponding company name
```suggestion
- symbol (text): the symbol representing a company name
- name (text): corresponding company name
```

2022-03-24 16:58 UTC, mirandaauhl commented on timescaledb/getting-started/add-data.md
> +* day_volume (int): number of shares traded each day, NULL values indicate the market is closed
```suggestion
* **`stocks_real_time`:** Stock data. Includes stock price quotes at every second during trading hours.
   * time (timestamptz): timestamp column incrementing second by second
   * symbol (text): symbols representing a company, mapped to company names in the `company` table
   * price (double precision): stock quote price for a company at the given timestamp
   * day_volume (int): number of shares traded each day, NULL values indicate the market is closed
```

2022-03-24 17:00 UTC, mirandaauhl commented on timescaledb/getting-started/add-data.md
> +- day_volume (int): number of shares traded each day, NULL values indicate the market is closed
```suggestion
* **`stocks_real_time`**: Stock data. Includes stock price quotes at every second during trading hours.
   *  time (timestamptz): timestamp column incrementing second by second
   *  symbol (text): symbols representing a company, mapped to company names in the `company` table
   * price (double precision): stock quote price for a company at the given timestamp
   * day_volume (int): number of shares traded each day, NULL values indicate the market is closed
```

2022-03-25 01:29 UTC, Loquacity approved these changes

2022-03-28 19:51 UTC, merged