Add instructions to disable compression
timescale/docs pull request #988
Opened 2022-03-31 05:51 UTC by Loquacity

# Description

With the compression docs now fully updated since the issue was raised, this addition became much simpler. So this adds a note to discuss how to disable compression.

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes https://github.com/timescale/docs/issues/490

2022-03-31 13:40 UTC, charislam requested changes

2022-03-31 13:40 UTC, charislam commented on timescaledb/how-to-guides/compression/about-compression.md
> +
```suggestion
```

Repeated from above

2022-04-01 05:44 UTC, Rajakavitha1 approved these changes

2022-04-01 14:41 UTC, charislam approved these changes

2022-04-04 02:34 UTC, merged