Add VPC CIDR mask constraint
timescale/docs pull request #989
Opened 2022-03-31 08:35 UTC by minkimipt

VPC CIDR mask has constraint of length. Mask is allowed to be in the
range between 16 and 28 and this needs to be reflected in documentation.

Background issue:
https://github.com/timescale/Support-Dev-Collab/issues/346

# Description

This needs to cover a gap in documentation that is not mentioning what length
CIDR is allowed to have during VPC creation.

# Version

Which documentation version does this PR apply to?

- [ ] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes #[insert issue link, if any]
https://github.com/timescale/Support-Dev-Collab/issues/346

2022-03-31 08:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/timescale/docs?pullRequest=989) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/timescale/docs?pullRequest=989) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/timescale/docs?pullRequest=989) it.</sub>

2022-04-01 00:43 UTC, Loquacity requested changes

2022-04-01 00:43 UTC, Loquacity commented on cloud/vpc-peering.md
> +        CIDR block of your AWS VPC from the AWS console. In this example, we use the
```suggestion
        CIDR block of your AWS VPC from the AWS console. This example uses the
```

2022-04-01 05:53 UTC, Rajakavitha1 approved these changes

2022-04-01 16:49 UTC, clarkbw commented on cloud/vpc-peering.md
> +        the range between 16 and 28 and that the CIDR block you choose for your
Only thing to note here for me is that it would be good for the console to protect users from entering anything out of this range.

2022-04-04 02:36 UTC, Loquacity approved these changes

2022-04-04 14:08 UTC, clarkbw commented on cloud/vpc-peering.md
> +        the range between 16 and 28 and that the CIDR block you choose for your
https://github.com/timescale/web-cloud/issues/2282 was filed for this originally and I filed https://github.com/timescale/web-cloud/issues/2307

2022-04-05 07:04 UTC, minkimipt commented
@Loquacity should I merge it int the `latest` branch? Or it should rather go into the `main`? With this last [merge](https://github.com/timescale/docs/pull/989/commits/713830f5d553b2a3862a934c0a8fd5f5805e2f5e) I am not sure.

2022-04-05 07:07 UTC, Loquacity commented
> @Loquacity should I merge it int the `latest` branch? Or it should rather go into the `main`? With this last [merge](https://github.com/timescale/docs/pull/989/commits/713830f5d553b2a3862a934c0a8fd5f5805e2f5e) I am not sure.

It needs to merge into `latest`.

2022-04-05 07:08 UTC, merged