Resource recommendation guide for Promscale traces
timescale/docs pull request #990
Opened 2022-03-31 10:07 UTC by VineethReddy02

# Description

Resource recommendation guide for Promscale traces. 

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes https://github.com/timescale/o11y-team-applications/issues/153

2022-04-01 00:49 UTC, Loquacity requested changes

2022-04-01 00:49 UTC, Loquacity commented on promscale/installation/recomm-guide.md
> +We recommend using the OpenTelemetry collector for ingesting the spans to Promscale by configureing the OTLP exporter and batch processor with below provided configuration this helps in retries for f
```suggestion
We recommend using the OpenTelemetry collector for ingesting the spans to 
Promscale. Use this configuration with the OTLP exporter and batch processor 
to help with retries for failed writes, and to batch the write requests to Promscale:
```

2022-04-01 00:49 UTC, Loquacity commented on promscale/installation/recomm-guide.md
> +This section describes the compute and disk requirements that are recommended for Promscale, based on the ingest rate and retention.
```suggestion
This section describes the compute and disk requirements that are 
recommended for Promscale, based on the ingest rate and retention.
```

2022-04-01 00:49 UTC, Loquacity commented on promscale/installation/recomm-guide.md
> +
```suggestion
You can calculate the `total disk size` based on retention and ingest rates with this formula:
```

2022-04-04 10:06 UTC, Rajakavitha1 approved these changes
Non blocker.  I see that thevrecommendation guide contains recommendations for Metrics as well but the title reads only traces.

2022-04-05 11:21 UTC, VineethReddy02 commented
@Rajakavitha1 this PR isn't part of tracing GA, the issues created by me, think of it as we do not have other dependencies over this, so we can merge it to master directly.

2022-04-05 13:02 UTC, niksajakovljevic commented on promscale/installation/recomm-guide.md
> +Uncompressed buffer based on the ingest rate.
+ WAL

2022-04-05 13:03 UTC, niksajakovljevic approved these changes

2022-04-05 13:05 UTC, niksajakovljevic commented on promscale/installation/recomm-guide.md
> +Uncompressed buffer based on the ingest rate.
Otherwise it's not really total disk size :) or maybe document that WAL is not included for whatever reason

2022-04-06 01:54 UTC, Loquacity approved these changes

2022-04-06 13:05 UTC, merged