added in forking to a new configuration
timescale/docs pull request #991
Opened 2022-03-31 17:11 UTC by ggodeke

# Description
Added in a line about forking to a new configuration. Also added a warning that forks do not stay in sync with the original service after forking. This is particularly important if you want your fork to become the primary; if you don't pause the service first, it will likely have new data that won't appear in the fork.

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes #[insert issue link, if any]

2022-03-31 20:54 UTC, charislam approved these changes
Non-blocking suggestions

2022-03-31 20:54 UTC, charislam commented on cloud/operations.md
> +data discrepancy between services.
```suggestion
service, pause your main service before forking to avoid any
data discrepancy between services.
```

2022-03-31 20:54 UTC, charislam commented on cloud/operations.md
> +    `Advanced options` link in the dialog.
```suggestion
1.  To change the configuration of your fork, click
    `Advanced options`. You can set different compute and
    storage options, separate from your original database.
```

2022-04-01 01:03 UTC, Loquacity requested changes

2022-04-01 01:03 UTC, Loquacity commented on cloud/operations.md
> +data written to the original service after the time of forking will not appear
```suggestion
data written to the original service after the time of forking does not appear 
```

2022-04-01 01:03 UTC, Loquacity commented on cloud/operations.md
> +in the fork. If you intend for the fork to assume operations from the original
```suggestion
in the fork. If you want the fork to assume operations from the original
```

2022-04-01 01:03 UTC, Loquacity commented on cloud/operations.md
> +service, you may want to pause your main service before forking to avoid any
```suggestion
service, you can pause your main service before you fork and avoid any
```

2022-04-01 05:42 UTC, Rajakavitha1 approved these changes

2022-04-13 05:48 UTC, Loquacity commented
@ggodeke Are you still working on this, or do you want us to take over?

2022-04-14 02:03 UTC, Loquacity approved these changes

2022-04-14 02:03 UTC, merged